// The descriptor, narrowed exactly once.
//
// Everything an application supplies arrives through this file (`ENGINEERING_RULES.md` §1),
// so every guarantee downstream of it rests on what is checked here. The checks
// are the ones anvil's own `well_formed()` makes — a duplicate bit, a duplicate
// name, an empty name, a bit out of range, a route naming a permission, a scope
// or a bucket that does not exist — made again on this side of the wire.
//
// Made again rather than trusted, because a descriptor is a FILE. It is copied
// between repositories, hand-edited by somebody in a hurry, and regenerated by a
// build that may be older than the server it claims to describe. A malformed one
// fails generation naming the key; the alternative is a generated module that
// compiles and lies, and the lie is an authority check reading the wrong bit.
//
// --- what is an error and what is a warning ---------------------------------
//
// A route naming a capability scope that does not exist is an error: the emitted
// type would require a `Capability<Scope>` of a scope with no minting call, and
// nothing would compile. The reverse — a scope no route requires, a bucket no
// route names — is a WARNING, and the reference descriptor is why. anvil limits
// by keys that are not route buckets and mints scopes for operations whose
// routes its emitter does not carry, so a hard failure there rejects anvil's own
// output. A dead entry still reads as coverage, so it is reported rather than
// dropped.
//
// The field-type and section checks (`docs/01-seams.md` §§7–8) are absent because
// the tables are: anvil records them as open rather than guessing at a shape, and
// a check against a table nobody emits is a check nothing can fail.

import type { Result } from "../core/result.js";
import { fail, ok } from "../core/result.js";
import {
    eventIdentifier,
    isSpellable,
    permissionIdentifier,
    routeIdentifier,
    sectionIdentifier,
    topicIdentifier,
} from "./names.js";

// The FORMAT version, bumped by anvil and never by an application. It answers
// "can this generator read this file at all", which is a different question from
// the one `hash` answers, and one number cannot answer both.
//
// 2 carried the content tables — `field_types`, `sections`, `topics`, `events`
// and `media` (`docs/01-seams.md` §§7–10, §12). 3 adds the two things a client
// was previously being told to write down itself: a route's declared RESPONSE
// shape (§4.3) and the media types a namespace ACCEPTS (§12). A descriptor of
// either earlier format is refused rather than read for the tables it does
// have: this generator is written against 3, and a file it was not written
// against is exactly what this number exists to stop it guessing at.
export const kSupportedFormat = 3;

// anvil stores 128 bits and never renumbers one.
const kMaxPermissionBit = 127;

export type ErrorCodeSpec = {
    readonly name: string;
    readonly value: number;
    readonly http: number;
    readonly stealth_hidden: boolean;
};

export type EnumeratorSpec = {
    readonly name: string;
    readonly value: number;
};

export type PermissionSpec = {
    readonly name: string;
    readonly bit: number;
};

export type LocaleSpec = {
    readonly tag: string;
    readonly collation: string;
    readonly rtl: boolean;
};

export type PageSpec = {
    readonly cursor: string;
    readonly limit_max: number;
};

export type RouteAccess = "public" | "authenticated" | "guarded" | "stealth";
export type RouteVisibility = "public" | "holder";
export type RouteMethod = "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE" | "ANY";

// --- what a route answers with ----------------------------------------------
//
// anvil writes its success bodies through a response binder, so the shape is a
// declaration the server is checked against rather than a comment beside the
// handler: writing a key that is not next, writing one of the wrong type or
// stopping early are `static_assert`s there (`http/response_writer.h`). That is
// what makes this table worth reading — a schema nothing enforced would be a
// description of bytes nobody sends, and generating types from one is worse
// than generating none, because the lie type-checks.
//
// The grammar is deliberately small, and the smallness is the point:
// `kind_name()` in anvil names six types, each of which is a distinction a
// CLIENT has to make rather than a JSON type. `uuid` and `string` are both JSON
// strings and one of them is parsed into a typed id; `time` is a JSON string a
// client turns into an instant. A vocabulary that collapsed them would describe
// the bytes correctly and the types uselessly.
//
// It is NOT re-declared as a closed set beyond what the emission branches on,
// for the reason the header above gives: a copy of anvil's enum is the copy
// nobody updates. A type this generator does not know is an error against the
// field that carries it rather than a table-wide failure, so a descriptor that
// grew a seventh kind names the one route hammer cannot type yet.
export type ResponseFieldType = "string" | "int" | "bool" | "uuid" | "time" | "strings";

export type ResponseFieldSpec = {
    readonly name: string;
    readonly type: ResponseFieldType;
    // A client's type for a nullable field is a DIFFERENT type, which is the
    // whole reason this is carried: a consumer told a field is always present
    // and handed a null crashes on the field it was told it could trust.
    readonly nullable: boolean;
};

export type ResponseKind = "object" | "array";

export type ResponseSpec = {
    readonly kind: ResponseKind;
    readonly fields: readonly ResponseFieldSpec[];
};

export type RouteSpec = {
    readonly id: string;
    readonly method: RouteMethod;
    readonly path: string;
    readonly access: RouteAccess;
    readonly visibility: RouteVisibility;
    readonly perms: readonly string[];
    readonly capability: string;
    readonly rate_limit: string;
    readonly idempotent: boolean;
    readonly page: PageSpec | null;

    // Null where anvil declared none, which is most routes: the binder is opt-in
    // per handler, and a route with no declaration emits no type rather than an
    // empty one. `unknown` at the call site is the honest answer there.
    readonly response: ResponseSpec | null;
};

export type CapabilityScopeSpec = {
    readonly name: string;
    readonly value: number;
    readonly single_use: boolean;
};

export type RateLimitSpec = {
    readonly bucket: string;
    readonly window_ms: number;
    readonly max_events: number;
};

export type LimitsSpec = {
    readonly upload_max_bytes: number;
    readonly body_max_bytes: number;
    readonly page_limit_max: number;
};

// --- the content tables -----------------------------------------------------
//
// Four of the five seams that describe what a client RENDERS rather than how it
// calls (`docs/01-seams.md` §§7–8, §10, §12). They are read the same way the
// transport tables are, with one difference that is worth stating rather than
// discovering: a vocabulary anvil owns is NOT re-declared here.
//
// `answer`, a section field's `type`, an event's `class`, a namespace's roles —
// each is a closed set server-side, and hammer could carry a copy of each and
// check against it. It does not, because a copy of an enum is the thing this
// whole seam exists to remove (`ENGINEERING_RULES.md` §1): the second copy is the one
// nobody updates, and it would turn a member anvil appends into a generation
// failure in every application on the day the server started sending it. They
// are read as strings, checked for what a string reaching the emitted file must
// be, and emitted as a union of exactly what the table holds — so the generated
// client's vocabulary is the descriptor's, and it is never larger.
//
// `visibility` is the exception, and only because the EMISSION branches on it.

export type FieldTypeFlags = {
    readonly options: boolean;
    readonly attachment: boolean;
    readonly ranged: boolean;
    readonly code_point_capped: boolean;
    readonly multi_line: boolean;
    readonly multi_select: boolean;
};

// `answer` is null for a PII type, which produces no answer a client reads back
// at all. `"text"` would be the shape of a value that has silently emptied
// itself, and a renderer handed one renders a control for it.
export type FieldTypeSpec = {
    readonly name: string;
    readonly code: number;
    readonly pii: boolean;
    readonly answer: string | null;
    readonly default_code_points: number;
    readonly flags: FieldTypeFlags;
};

export type SectionFieldSpec = {
    readonly key: string;
    readonly type: string;
    // Indexed by the locale table's order, which is persisted and append-only
    // (§5). Never keyed by tag, because the stored index is what everything
    // else in the descriptor is keyed by.
    readonly labels: readonly string[];
    readonly max_code_points: number;
    readonly localized: boolean;
    readonly required: boolean;
    readonly choices: readonly string[];
};

export type AspectSpec = {
    readonly num: number;
    readonly den: number;
};

export type SectionImageSpec = {
    readonly slot: string;
    readonly labels: readonly string[];
    readonly min_width: number;
    readonly min_height: number;
    readonly aspect: AspectSpec | null;
};

export type SectionSpec = {
    readonly key: string;
    readonly site_path: string;
    readonly fields: readonly SectionFieldSpec[];
    readonly images: readonly SectionImageSpec[];
};

// A topic's `visibility` is the one content-table field read as a closed set
// rather than as a string, and the reason is that the EMISSION branches on it:
// it selects between emitting a key and withholding one. It is deliberately the
// same type the route table uses, because it is one rule (§4.1) applied to two
// tables — subscribing to a topic is the disclosure the way calling a route is.
export type TopicVisibility = RouteVisibility;

export type TopicSpec = {
    readonly key: string;
    readonly code: number;
    readonly fanout: string;
    readonly scope: string;
    readonly default_channels: readonly string[];
    readonly coalesce_window_s: number;
    readonly retention_days: number;
    readonly user_optional: boolean;
    readonly stealth_on_denial: boolean;
    readonly perms: readonly string[];
    readonly visibility: TopicVisibility;
};

export type DimensionSpec = {
    readonly name: string;
    readonly values: readonly string[];
};

export type EventSpec = {
    readonly name: string;
    readonly code: number;
    readonly class: string;
    readonly requires_consent: boolean;
    readonly dimensions: readonly DimensionSpec[];
};

export type MediaRoleSpec = {
    readonly role: string;
    readonly width: number;
};

export type MediaNamespaceSpec = {
    readonly ns: string;

    // The media types this namespace will take, in the order anvil declared
    // them. It is the server's list and the client's is a copy of it, which is
    // the only arrangement in which the `accept` attribute on a file input and
    // the check that runs before a byte is sent cannot disagree with what the
    // upload will actually be refused for.
    readonly accepts: readonly string[];

    readonly roles: readonly MediaRoleSpec[];
};

export type MediaTable = {
    readonly default_role: string;
    readonly namespaces: readonly MediaNamespaceSpec[];
};

export type ErrorCodeTable = {
    readonly max: number;
    readonly codes: readonly ErrorCodeSpec[];
};

// The keys are the descriptor's, unchanged. A reader that renamed them would be
// a second spelling of the format, and a reader is the one place where the file
// on disk and the type in the source have to be readable against each other.
export type Tables = {
    readonly error_codes: ErrorCodeTable;
    readonly validation_reasons: readonly EnumeratorSpec[];
    readonly permissions: readonly PermissionSpec[];
    readonly locales: readonly LocaleSpec[];
    readonly routes: readonly RouteSpec[];
    readonly capability_scopes: readonly CapabilityScopeSpec[];
    readonly rate_limits: readonly RateLimitSpec[];
    readonly limits: LimitsSpec;
    readonly field_types: readonly FieldTypeSpec[];
    readonly sections: readonly SectionSpec[];
    readonly topics: readonly TopicSpec[];
    readonly events: readonly EventSpec[];
    readonly media: MediaTable;
};

export type Descriptor = {
    readonly descriptor: number;
    readonly emitted_by: string;
    readonly app: { readonly name: string; readonly version: string };
    readonly hash: string;
    readonly tables: Tables;
};

export type DescriptorIssue =
    | "not-json"
    | "not-an-object"
    | "not-an-array"
    | "not-a-string"
    | "not-an-integer"
    | "not-a-boolean"
    | "unsupported-format"
    | "empty"
    | "not-spellable"
    | "not-plain-text"
    | "not-a-sha256"
    | "duplicate-name"
    | "duplicate-value"
    | "duplicate-bit"
    | "out-of-range"
    | "above-maximum"
    | "not-positive"
    | "unknown-member"
    | "unusable-method"
    | "identifier-collision"
    | "path-not-absolute"
    | "path-not-a-route-pattern"
    | "malformed-path-parameter"
    | "duplicate-path-parameter"
    | "unknown-permission"
    | "unknown-capability-scope"
    | "unknown-rate-limit-bucket"
    | "unknown-media-role"
    | "not-a-media-type"
    | "duplicate-field"
    | "visibility-contradicts-perms"
    | "no-route-requires-it"
    | "no-route-names-it";

// The key is a path into the file, so the CLI can name it and a person can open
// the file and look at it. It is not a sentence: this is a build-time tool, and
// the words a person reads still belong to whoever knows the audience.
export type DescriptorProblem = {
    readonly key: string;
    readonly issue: DescriptorIssue;
};

export type DescriptorReading = {
    readonly descriptor: Descriptor;
    readonly warnings: readonly DescriptorProblem[];
};

type Raw = Readonly<Record<string, unknown>>;

function asObject(value: unknown): Raw | null {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        return null;
    }
    return value as Raw;
}

class Collector {
    readonly errors: DescriptorProblem[] = [];
    readonly warnings: DescriptorProblem[] = [];

    error(key: string, issue: DescriptorIssue): void {
        this.errors.push({ key, issue });
    }

    warn(key: string, issue: DescriptorIssue): void {
        this.warnings.push({ key, issue });
    }

    object(value: unknown, key: string): Raw | null {
        const object = asObject(value);
        if (object === null) {
            this.error(key, "not-an-object");
        }
        return object;
    }

    array(value: unknown, key: string): readonly unknown[] | null {
        if (!Array.isArray(value)) {
            this.error(key, "not-an-array");
            return null;
        }
        return value;
    }

    string(holder: Raw, field: string, key: string): string | null {
        const value = holder[field];
        if (typeof value !== "string") {
            this.error(key, "not-a-string");
            return null;
        }
        return value;
    }

    integer(holder: Raw, field: string, key: string): number | null {
        const value = holder[field];
        if (typeof value !== "number" || !Number.isSafeInteger(value)) {
            this.error(key, "not-an-integer");
            return null;
        }
        return value;
    }

    boolean(holder: Raw, field: string, key: string): boolean | null {
        const value = holder[field];
        if (typeof value !== "boolean") {
            this.error(key, "not-a-boolean");
            return null;
        }
        return value;
    }

    strings(holder: Raw, field: string, key: string): string[] | null {
        const value = this.array(holder[field], key);
        if (value === null) {
            return null;
        }
        const out: string[] = [];
        for (let i = 0; i < value.length; i += 1) {
            const item = value[i];
            if (typeof item !== "string") {
                this.error(`${key}[${i}]`, "not-a-string");
                continue;
            }
            out.push(item);
        }
        return out;
    }

    member<T extends string>(
        holder: Raw,
        field: string,
        key: string,
        allowed: readonly T[],
    ): T | null {
        const value = holder[field];
        if (typeof value !== "string") {
            this.error(key, "not-a-string");
            return null;
        }
        const found = allowed.find((candidate) => candidate === value);
        if (found === undefined) {
            this.error(key, "unknown-member");
            return null;
        }
        return found;
    }

    // A name that is empty, or that cannot become an identifier without becoming
    // some other name's identifier. Both are reported against the name rather
    // than against the emission, because the emitter is not the thing that is
    // wrong.
    name(value: string, key: string): void {
        if (value.length === 0) {
            this.error(key, "empty");
            return;
        }
        if (!isSpellable(value)) {
            this.error(key, "not-spellable");
        }
    }
}

// --- structure --------------------------------------------------------------

function readErrorCodes(collector: Collector, raw: unknown): ErrorCodeTable | null {
    const table = collector.object(raw, "tables.error_codes");
    if (table === null) {
        return null;
    }
    const max = collector.integer(table, "max", "tables.error_codes.max");
    const entries = collector.array(table["codes"], "tables.error_codes.codes");
    if (max === null || entries === null) {
        return null;
    }

    const codes: ErrorCodeSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.error_codes.codes[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const value = collector.integer(entry, "value", `${key}.value`);
        const http = collector.integer(entry, "http", `${key}.http`);
        const hidden = collector.boolean(entry, "stealth_hidden", `${key}.stealth_hidden`);
        if (name === null || value === null || http === null || hidden === null) {
            continue;
        }
        codes.push({ name, value, http, stealth_hidden: hidden });
    }
    return { max, codes };
}

function readEnumerators(collector: Collector, raw: unknown, at: string): EnumeratorSpec[] | null {
    const entries = collector.array(raw, at);
    if (entries === null) {
        return null;
    }
    const out: EnumeratorSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `${at}[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const value = collector.integer(entry, "value", `${key}.value`);
        if (name === null || value === null) {
            continue;
        }
        out.push({ name, value });
    }
    return out;
}

function readPermissions(collector: Collector, raw: unknown): PermissionSpec[] | null {
    const entries = collector.array(raw, "tables.permissions");
    if (entries === null) {
        return null;
    }
    const out: PermissionSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.permissions[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const bit = collector.integer(entry, "bit", `${key}.bit`);
        if (name === null || bit === null) {
            continue;
        }
        out.push({ name, bit });
    }
    return out;
}

function readLocales(collector: Collector, raw: unknown): LocaleSpec[] | null {
    const entries = collector.array(raw, "tables.locales");
    if (entries === null) {
        return null;
    }
    const out: LocaleSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.locales[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const tag = collector.string(entry, "tag", `${key}.tag`);
        const collation = collector.string(entry, "collation", `${key}.collation`);
        const rtl = collector.boolean(entry, "rtl", `${key}.rtl`);
        if (tag === null || collation === null || rtl === null) {
            continue;
        }
        out.push({ tag, collation, rtl });
    }
    return out;
}

const kAccess: readonly RouteAccess[] = ["public", "authenticated", "guarded", "stealth"];
const kVisibility: readonly RouteVisibility[] = ["public", "holder"];
const kMethods: readonly RouteMethod[] = ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "ANY"];
const kResponseKinds: readonly ResponseKind[] = ["object", "array"];
const kResponseFieldTypes: readonly ResponseFieldType[] = [
    "string",
    "int",
    "bool",
    "uuid",
    "time",
    "strings",
];

function readPage(collector: Collector, raw: unknown, at: string): PageSpec | null | undefined {
    if (raw === null || raw === undefined) {
        return null;
    }
    const page = collector.object(raw, at);
    if (page === null) {
        return undefined;
    }
    const cursor = collector.string(page, "cursor", `${at}.cursor`);
    const limitMax = collector.integer(page, "limit_max", `${at}.limit_max`);
    if (cursor === null || limitMax === null) {
        return undefined;
    }
    return { cursor, limit_max: limitMax };
}

// `undefined` is the sentinel for "malformed", the way `readPage` uses it, so
// that a route with a broken schema fails generation rather than silently
// becoming an untyped one. A null response is a route anvil declared none for,
// which is not a defect.
function readResponse(
    collector: Collector,
    raw: unknown,
    at: string,
): ResponseSpec | null | undefined {
    if (raw === null || raw === undefined) {
        return null;
    }
    const response = collector.object(raw, at);
    if (response === null) {
        return undefined;
    }
    const kind = collector.member(response, "kind", `${at}.kind`, kResponseKinds);
    const rawFields = collector.array(response["fields"], `${at}.fields`);
    if (kind === null || rawFields === null) {
        return undefined;
    }

    const fields: ResponseFieldSpec[] = [];
    for (let i = 0; i < rawFields.length; i += 1) {
        const key = `${at}.fields[${i}]`;
        const entry = collector.object(rawFields[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const type = collector.member(entry, "type", `${key}.type`, kResponseFieldTypes);
        const nullable = collector.boolean(entry, "nullable", `${key}.nullable`);
        if (name === null || type === null || nullable === null) {
            continue;
        }
        // A key that is not a key. It is emitted as a quoted property name so
        // any text would compile, but a body key is also what a call site reads
        // by hand, and an empty one is a field nothing can name.
        if (name.length === 0) {
            collector.error(`${key}.name`, "empty");
            continue;
        }
        fields.push({ name, type, nullable });
    }

    // A declared response with no field is not an object shape; it is a
    // declaration somebody started and did not finish. anvil emits `null` for
    // "no declaration", so this cannot be that.
    if (fields.length === 0) {
        collector.error(`${at}.fields`, "empty");
        return undefined;
    }
    if (fields.length !== rawFields.length) {
        return undefined;
    }
    return { kind, fields };
}

function readRoutes(collector: Collector, raw: unknown): RouteSpec[] | null {
    const entries = collector.array(raw, "tables.routes");
    if (entries === null) {
        return null;
    }
    const out: RouteSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.routes[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const id = collector.string(entry, "id", `${key}.id`);
        const method = collector.member(entry, "method", `${key}.method`, kMethods);
        const path = collector.string(entry, "path", `${key}.path`);
        const access = collector.member(entry, "access", `${key}.access`, kAccess);
        const visibility = collector.member(entry, "visibility", `${key}.visibility`, kVisibility);
        const capability = collector.string(entry, "capability", `${key}.capability`);
        const rateLimit = collector.string(entry, "rate_limit", `${key}.rate_limit`);
        const idempotent = collector.boolean(entry, "idempotent", `${key}.idempotent`);
        const page = readPage(collector, entry["page"], `${key}.page`);
        const response = readResponse(collector, entry["response"], `${key}.response`);
        const rawPerms = collector.array(entry["perms"], `${key}.perms`);

        const perms: string[] = [];
        if (rawPerms !== null) {
            for (let p = 0; p < rawPerms.length; p += 1) {
                const perm = rawPerms[p];
                if (typeof perm !== "string") {
                    collector.error(`${key}.perms[${p}]`, "not-a-string");
                    continue;
                }
                perms.push(perm);
            }
        }

        if (
            id === null ||
            method === null ||
            path === null ||
            access === null ||
            visibility === null ||
            capability === null ||
            rateLimit === null ||
            idempotent === null ||
            page === undefined ||
            response === undefined ||
            rawPerms === null
        ) {
            continue;
        }

        out.push({
            id,
            method,
            path,
            access,
            visibility,
            perms,
            capability,
            rate_limit: rateLimit,
            idempotent,
            page,
            response,
        });
    }
    return out;
}

function readCapabilityScopes(collector: Collector, raw: unknown): CapabilityScopeSpec[] | null {
    const entries = collector.array(raw, "tables.capability_scopes");
    if (entries === null) {
        return null;
    }
    const out: CapabilityScopeSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.capability_scopes[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const value = collector.integer(entry, "value", `${key}.value`);
        const singleUse = collector.boolean(entry, "single_use", `${key}.single_use`);
        if (name === null || value === null || singleUse === null) {
            continue;
        }
        out.push({ name, value, single_use: singleUse });
    }
    return out;
}

function readRateLimits(collector: Collector, raw: unknown): RateLimitSpec[] | null {
    const entries = collector.array(raw, "tables.rate_limits");
    if (entries === null) {
        return null;
    }
    const out: RateLimitSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.rate_limits[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const bucket = collector.string(entry, "bucket", `${key}.bucket`);
        const windowMs = collector.integer(entry, "window_ms", `${key}.window_ms`);
        const maxEvents = collector.integer(entry, "max_events", `${key}.max_events`);
        if (bucket === null || windowMs === null || maxEvents === null) {
            continue;
        }
        out.push({ bucket, window_ms: windowMs, max_events: maxEvents });
    }
    return out;
}

function readLimits(collector: Collector, raw: unknown): LimitsSpec | null {
    const limits = collector.object(raw, "tables.limits");
    if (limits === null) {
        return null;
    }
    const upload = collector.integer(limits, "upload_max_bytes", "tables.limits.upload_max_bytes");
    const body = collector.integer(limits, "body_max_bytes", "tables.limits.body_max_bytes");
    const page = collector.integer(limits, "page_limit_max", "tables.limits.page_limit_max");
    if (upload === null || body === null || page === null) {
        return null;
    }
    return { upload_max_bytes: upload, body_max_bytes: body, page_limit_max: page };
}

// Six named booleans rather than the byte anvil stores, so they are read one at
// a time and each is reported against its own key: a client carrying a copy of a
// bitmask is a client carrying a copy of an enum.
function readFieldTypeFlags(collector: Collector, raw: unknown, at: string): FieldTypeFlags | null {
    const flags = collector.object(raw, at);
    if (flags === null) {
        return null;
    }
    const options = collector.boolean(flags, "options", `${at}.options`);
    const attachment = collector.boolean(flags, "attachment", `${at}.attachment`);
    const ranged = collector.boolean(flags, "ranged", `${at}.ranged`);
    const capped = collector.boolean(flags, "code_point_capped", `${at}.code_point_capped`);
    const multiLine = collector.boolean(flags, "multi_line", `${at}.multi_line`);
    const multiSelect = collector.boolean(flags, "multi_select", `${at}.multi_select`);
    if (
        options === null ||
        attachment === null ||
        ranged === null ||
        capped === null ||
        multiLine === null ||
        multiSelect === null
    ) {
        return null;
    }
    return {
        options,
        attachment,
        ranged,
        code_point_capped: capped,
        multi_line: multiLine,
        multi_select: multiSelect,
    };
}

// `null` is a value here and not an omission — a PII type produces no answer at
// all — so it is read before the string check rather than falling into it.
function readAnswerKind(collector: Collector, raw: unknown, at: string): string | null | undefined {
    if (raw === null) {
        return null;
    }
    if (typeof raw !== "string") {
        collector.error(at, "not-a-string");
        return undefined;
    }
    return raw;
}

function readFieldTypes(collector: Collector, raw: unknown): FieldTypeSpec[] | null {
    const entries = collector.array(raw, "tables.field_types");
    if (entries === null) {
        return null;
    }
    const out: FieldTypeSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.field_types[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const code = collector.integer(entry, "code", `${key}.code`);
        const pii = collector.boolean(entry, "pii", `${key}.pii`);
        const answer = readAnswerKind(collector, entry["answer"], `${key}.answer`);
        const defaults = collector.integer(
            entry,
            "default_code_points",
            `${key}.default_code_points`,
        );
        const flags = readFieldTypeFlags(collector, entry["flags"], `${key}.flags`);

        if (
            name === null ||
            code === null ||
            pii === null ||
            answer === undefined ||
            defaults === null ||
            flags === null
        ) {
            continue;
        }

        out.push({ name, code, pii, answer, default_code_points: defaults, flags });
    }
    return out;
}

function readSectionFields(collector: Collector, raw: unknown, at: string): SectionFieldSpec[] | null {
    const entries = collector.array(raw, at);
    if (entries === null) {
        return null;
    }
    const out: SectionFieldSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `${at}[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const fieldKey = collector.string(entry, "key", `${key}.key`);
        const type = collector.string(entry, "type", `${key}.type`);
        const labels = collector.strings(entry, "labels", `${key}.labels`);
        const maxCodePoints = collector.integer(
            entry,
            "max_code_points",
            `${key}.max_code_points`,
        );
        const localized = collector.boolean(entry, "localized", `${key}.localized`);
        const required = collector.boolean(entry, "required", `${key}.required`);
        const choices = collector.strings(entry, "choices", `${key}.choices`);
        if (
            fieldKey === null ||
            type === null ||
            labels === null ||
            maxCodePoints === null ||
            localized === null ||
            required === null ||
            choices === null
        ) {
            continue;
        }
        out.push({
            key: fieldKey,
            type,
            labels,
            max_code_points: maxCodePoints,
            localized,
            required,
            choices,
        });
    }
    return out;
}

// Null when either half is zero, never `{ num: 0, den: 0 }`: an object is always
// truthy, and a slot with no constraint rendered as "shaped 0:0" is a
// requirement nobody can satisfy or recognise as nothing being asked.
function readAspect(collector: Collector, raw: unknown, at: string): AspectSpec | null | undefined {
    if (raw === null || raw === undefined) {
        return null;
    }
    const aspect = collector.object(raw, at);
    if (aspect === null) {
        return undefined;
    }
    const num = collector.integer(aspect, "num", `${at}.num`);
    const den = collector.integer(aspect, "den", `${at}.den`);
    if (num === null || den === null) {
        return undefined;
    }
    return { num, den };
}

function readSectionImages(collector: Collector, raw: unknown, at: string): SectionImageSpec[] | null {
    const entries = collector.array(raw, at);
    if (entries === null) {
        return null;
    }
    const out: SectionImageSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `${at}[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const slot = collector.string(entry, "slot", `${key}.slot`);
        const labels = collector.strings(entry, "labels", `${key}.labels`);
        const minWidth = collector.integer(entry, "min_width", `${key}.min_width`);
        const minHeight = collector.integer(entry, "min_height", `${key}.min_height`);
        const aspect = readAspect(collector, entry["aspect"], `${key}.aspect`);
        if (
            slot === null ||
            labels === null ||
            minWidth === null ||
            minHeight === null ||
            aspect === undefined
        ) {
            continue;
        }
        out.push({ slot, labels, min_width: minWidth, min_height: minHeight, aspect });
    }
    return out;
}

function readSections(collector: Collector, raw: unknown): SectionSpec[] | null {
    const entries = collector.array(raw, "tables.sections");
    if (entries === null) {
        return null;
    }
    const out: SectionSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.sections[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const sectionKey = collector.string(entry, "key", `${key}.key`);
        const sitePath = collector.string(entry, "site_path", `${key}.site_path`);
        const fields = readSectionFields(collector, entry["fields"], `${key}.fields`);
        const images = readSectionImages(collector, entry["images"], `${key}.images`);
        if (sectionKey === null || sitePath === null || fields === null || images === null) {
            continue;
        }
        out.push({ key: sectionKey, site_path: sitePath, fields, images });
    }
    return out;
}

function readTopics(collector: Collector, raw: unknown): TopicSpec[] | null {
    const entries = collector.array(raw, "tables.topics");
    if (entries === null) {
        return null;
    }
    const out: TopicSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.topics[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const topicKey = collector.string(entry, "key", `${key}.key`);
        const code = collector.integer(entry, "code", `${key}.code`);
        const fanout = collector.string(entry, "fanout", `${key}.fanout`);
        const scope = collector.string(entry, "scope", `${key}.scope`);
        const channels = collector.strings(entry, "default_channels", `${key}.default_channels`);
        const coalesce = collector.integer(entry, "coalesce_window_s", `${key}.coalesce_window_s`);
        const retention = collector.integer(entry, "retention_days", `${key}.retention_days`);
        const optional = collector.boolean(entry, "user_optional", `${key}.user_optional`);
        const stealth = collector.boolean(entry, "stealth_on_denial", `${key}.stealth_on_denial`);
        const perms = collector.strings(entry, "perms", `${key}.perms`);
        const visibility = collector.member(entry, "visibility", `${key}.visibility`, kVisibility);

        if (
            topicKey === null ||
            code === null ||
            fanout === null ||
            scope === null ||
            channels === null ||
            coalesce === null ||
            retention === null ||
            optional === null ||
            stealth === null ||
            perms === null ||
            visibility === null
        ) {
            continue;
        }

        out.push({
            key: topicKey,
            code,
            fanout,
            scope,
            default_channels: channels,
            coalesce_window_s: coalesce,
            retention_days: retention,
            user_optional: optional,
            stealth_on_denial: stealth,
            perms,
            visibility,
        });
    }
    return out;
}

function readDimensions(collector: Collector, raw: unknown, at: string): DimensionSpec[] | null {
    const entries = collector.array(raw, at);
    if (entries === null) {
        return null;
    }
    const out: DimensionSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `${at}[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const values = collector.strings(entry, "values", `${key}.values`);
        if (name === null || values === null) {
            continue;
        }
        out.push({ name, values });
    }
    return out;
}

function readEvents(collector: Collector, raw: unknown): EventSpec[] | null {
    const entries = collector.array(raw, "tables.events");
    if (entries === null) {
        return null;
    }
    const out: EventSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.events[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const name = collector.string(entry, "name", `${key}.name`);
        const code = collector.integer(entry, "code", `${key}.code`);
        const eventClass = collector.string(entry, "class", `${key}.class`);
        const consent = collector.boolean(entry, "requires_consent", `${key}.requires_consent`);
        const dimensions = readDimensions(collector, entry["dimensions"], `${key}.dimensions`);
        if (
            name === null ||
            code === null ||
            eventClass === null ||
            consent === null ||
            dimensions === null
        ) {
            continue;
        }
        out.push({ name, code, class: eventClass, requires_consent: consent, dimensions });
    }
    return out;
}

function readMedia(collector: Collector, raw: unknown): MediaTable | null {
    const table = collector.object(raw, "tables.media");
    if (table === null) {
        return null;
    }
    const defaultRole = collector.string(table, "default_role", "tables.media.default_role");
    const entries = collector.array(table["namespaces"], "tables.media.namespaces");
    if (defaultRole === null || entries === null) {
        return null;
    }

    const namespaces: MediaNamespaceSpec[] = [];
    for (let i = 0; i < entries.length; i += 1) {
        const key = `tables.media.namespaces[${i}]`;
        const entry = collector.object(entries[i], key);
        if (entry === null) {
            continue;
        }
        const ns = collector.string(entry, "ns", `${key}.ns`);
        const accepts = collector.strings(entry, "accepts", `${key}.accepts`);
        const rawRoles = collector.array(entry["roles"], `${key}.roles`);
        if (ns === null || accepts === null || rawRoles === null) {
            continue;
        }
        const roles: MediaRoleSpec[] = [];
        for (let r = 0; r < rawRoles.length; r += 1) {
            const roleKey = `${key}.roles[${r}]`;
            const rawRole = collector.object(rawRoles[r], roleKey);
            if (rawRole === null) {
                continue;
            }
            const role = collector.string(rawRole, "role", `${roleKey}.role`);
            const width = collector.integer(rawRole, "width", `${roleKey}.width`);
            if (role === null || width === null) {
                continue;
            }
            roles.push({ role, width });
        }
        namespaces.push({ ns, accepts, roles });
    }
    return { default_role: defaultRole, namespaces };
}

// --- what characters may reach the emitted file -----------------------------
//
// Every string the generator writes into the output goes through
// `JSON.stringify`, which escapes a quote, a backslash and a newline — so an
// emitted module cannot be broken out of by a descriptor value. That is the
// SECOND line of defence and not the first. These classes are the first: a
// route pattern, a locale tag, a collation and a cursor field are the only
// descriptor strings that do not have to become an identifier, and without a
// class of their own they would be the only ones reaching the file on the
// strength of one `JSON.stringify` call that a later refactor could drop.
//
// They are deliberately tight. A rejection is a loud build failure naming the
// key, which costs minutes; the other failure is a generated module that is not
// what anybody reviewed.
const kRoutePattern = /^\/[A-Za-z0-9\-._~/{}]*$/;
const kLocaleTag = /^[A-Za-z][A-Za-z0-9]*(?:-[A-Za-z0-9]+)*$/;
const kFieldName = /^[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*$/;

// RFC 6838 restricted-name characters, lowercase, one solidus, no parameters.
const kMediaType = /^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*$/;

// A label and a choice are the two descriptor strings that cannot have a class
// of their own: they are words in whatever language the application is written
// in, and a class tight enough to be worth having would refuse a script. What
// they can be refused for is characters that are not text — the C0 and C1
// controls, and U+2028 and U+2029, which `JSON.stringify` does NOT escape and
// which a parser older than the JSON-superset rule reads as a line break in the
// middle of a string literal. Everything else about them rests on that
// escaping, which the emit suite asserts against a hostile value.
const kNotPlainText = /[\u0000-\u001F\u007F-\u009F\u2028\u2029]/;

// --- semantics --------------------------------------------------------------

// A path parameter is `{name}`, and nothing else in the path may hold a brace.
// The names are what the emitted `RouteParams` type is built from, so a path
// that cannot be parsed here is a route whose call site would take `never`.
function pathParameters(collector: Collector, path: string, key: string): readonly string[] {
    if (!path.startsWith("/")) {
        collector.error(key, "path-not-absolute");
    }
    if (!kRoutePattern.test(path)) {
        collector.error(key, "path-not-a-route-pattern");
    }

    const names: string[] = [];
    const seen = new Set<string>();
    let at = 0;

    while (at < path.length) {
        const open = path.indexOf("{", at);
        if (open < 0) {
            if (path.indexOf("}", at) >= 0) {
                collector.error(key, "malformed-path-parameter");
            }
            break;
        }
        const close = path.indexOf("}", open + 1);
        if (close < 0) {
            collector.error(key, "malformed-path-parameter");
            break;
        }
        const name = path.slice(open + 1, close);
        if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(name)) {
            collector.error(key, "malformed-path-parameter");
        } else if (seen.has(name)) {
            collector.error(key, "duplicate-path-parameter");
        } else {
            seen.add(name);
            names.push(name);
        }
        at = close + 1;
    }

    return names;
}

export function pathParametersOf(path: string): readonly string[] {
    return pathParameters(new Collector(), path, "");
}

type Seen = {
    readonly names: Set<string>;
    readonly values: Set<number>;
    readonly identifiers: Set<string>;
};

function newSeen(): Seen {
    return { names: new Set<string>(), values: new Set<number>(), identifiers: new Set<string>() };
}

function checkName(collector: Collector, seen: Seen, name: string, key: string): void {
    collector.name(name, key);
    if (seen.names.has(name)) {
        collector.error(key, "duplicate-name");
        return;
    }
    seen.names.add(name);
}

function checkValue(collector: Collector, seen: Seen, value: number, key: string): void {
    if (value < 0) {
        collector.error(key, "out-of-range");
        return;
    }
    if (seen.values.has(value)) {
        collector.error(key, "duplicate-value");
        return;
    }
    seen.values.add(value);
}

function checkErrorCodes(collector: Collector, table: ErrorCodeTable): void {
    const seen = newSeen();
    for (let i = 0; i < table.codes.length; i += 1) {
        const code = table.codes[i];
        if (code === undefined) {
            continue;
        }
        const key = `tables.error_codes.codes[${i}]`;
        checkName(collector, seen, code.name, `${key}.name`);
        checkValue(collector, seen, code.value, `${key}.value`);
        if (code.value > table.max) {
            collector.error(`${key}.value`, "above-maximum");
        }
    }
}

function checkEnumerators(
    collector: Collector,
    entries: readonly EnumeratorSpec[],
    at: string,
): void {
    const seen = newSeen();
    for (let i = 0; i < entries.length; i += 1) {
        const entry = entries[i];
        if (entry === undefined) {
            continue;
        }
        checkName(collector, seen, entry.name, `${at}[${i}].name`);
        checkValue(collector, seen, entry.value, `${at}[${i}].value`);
    }
}

function checkPermissions(collector: Collector, permissions: readonly PermissionSpec[]): void {
    const seen = newSeen();
    for (let i = 0; i < permissions.length; i += 1) {
        const permission = permissions[i];
        if (permission === undefined) {
            continue;
        }
        const key = `tables.permissions[${i}]`;
        checkName(collector, seen, permission.name, `${key}.name`);

        if (permission.bit < 0 || permission.bit > kMaxPermissionBit) {
            collector.error(`${key}.bit`, "out-of-range");
        } else if (seen.values.has(permission.bit)) {
            collector.error(`${key}.bit`, "duplicate-bit");
        } else {
            seen.values.add(permission.bit);
        }

        // Two names that differ only by separator or case land on one `const`,
        // and the second would silently shadow the first in the emitted module.
        const identifier = permissionIdentifier(permission.name);
        if (seen.identifiers.has(identifier)) {
            collector.error(`${key}.name`, "identifier-collision");
        } else {
            seen.identifiers.add(identifier);
        }
    }
}

function checkLocales(collector: Collector, locales: readonly LocaleSpec[]): void {
    if (locales.length === 0) {
        collector.error("tables.locales", "empty");
    }
    const seen = new Set<string>();
    for (let i = 0; i < locales.length; i += 1) {
        const locale = locales[i];
        if (locale === undefined) {
            continue;
        }
        const key = `tables.locales[${i}]`;
        if (locale.tag.length === 0) {
            collector.error(`${key}.tag`, "empty");
        } else if (!kLocaleTag.test(locale.tag)) {
            collector.error(`${key}.tag`, "not-spellable");
        } else if (seen.has(locale.tag)) {
            collector.error(`${key}.tag`, "duplicate-name");
        } else {
            seen.add(locale.tag);
        }
        if (locale.collation.length === 0) {
            collector.error(`${key}.collation`, "empty");
        } else if (!kLocaleTag.test(locale.collation)) {
            collector.error(`${key}.collation`, "not-spellable");
        }
    }
}

function checkCapabilityScopes(collector: Collector, scopes: readonly CapabilityScopeSpec[]): void {
    const seen = newSeen();
    for (let i = 0; i < scopes.length; i += 1) {
        const scope = scopes[i];
        if (scope === undefined) {
            continue;
        }
        const key = `tables.capability_scopes[${i}]`;
        checkName(collector, seen, scope.name, `${key}.name`);
        checkValue(collector, seen, scope.value, `${key}.value`);
    }
}

function checkRateLimits(collector: Collector, buckets: readonly RateLimitSpec[]): void {
    const seen = newSeen();
    for (let i = 0; i < buckets.length; i += 1) {
        const bucket = buckets[i];
        if (bucket === undefined) {
            continue;
        }
        const key = `tables.rate_limits[${i}]`;
        checkName(collector, seen, bucket.bucket, `${key}.bucket`);
        if (bucket.window_ms <= 0) {
            collector.error(`${key}.window_ms`, "not-positive");
        }
        if (bucket.max_events <= 0) {
            collector.error(`${key}.max_events`, "not-positive");
        }
    }
}

function checkLimits(collector: Collector, limits: LimitsSpec): void {
    if (limits.upload_max_bytes <= 0) {
        collector.error("tables.limits.upload_max_bytes", "not-positive");
    }
    if (limits.body_max_bytes <= 0) {
        collector.error("tables.limits.body_max_bytes", "not-positive");
    }
    if (limits.page_limit_max <= 0) {
        collector.error("tables.limits.page_limit_max", "not-positive");
    }
}

// One label per declared locale, in the locale table's order (§5). A shorter
// array is an index out of range the moment a staff editor switches language,
// which is the defect nobody sees in the locale they develop in.
function checkLabels(
    collector: Collector,
    labels: readonly string[],
    locales: number,
    key: string,
): void {
    if (labels.length !== locales) {
        collector.error(key, "out-of-range");
    }
    for (let i = 0; i < labels.length; i += 1) {
        const label = labels[i];
        if (label !== undefined && kNotPlainText.test(label)) {
            collector.error(`${key}[${i}]`, "not-plain-text");
        }
    }
}

function checkFieldTypes(collector: Collector, types: readonly FieldTypeSpec[]): void {
    const seen = newSeen();
    const answers = new Set<string>();
    for (let i = 0; i < types.length; i += 1) {
        const type = types[i];
        if (type === undefined) {
            continue;
        }
        const key = `tables.field_types[${i}]`;
        checkName(collector, seen, type.name, `${key}.name`);
        checkValue(collector, seen, type.code, `${key}.code`);

        // The answer kind is anvil's vocabulary and is emitted as a union of
        // what the table holds, so the only question here is whether it can
        // reach the file.
        if (type.answer !== null && !answers.has(type.answer)) {
            collector.name(type.answer, `${key}.answer`);
            answers.add(type.answer);
        }

        // A PII type produces no answer at all. The two say the same thing and
        // a client branches on both, so a descriptor where they disagree is one
        // whose renderer would draw a control for a value it can never read.
        if (type.pii === (type.answer !== null)) {
            collector.error(`${key}.answer`, "unknown-member");
        }

        if (type.default_code_points < 0) {
            collector.error(`${key}.default_code_points`, "out-of-range");
        }
    }
}

function checkSections(collector: Collector, sections: readonly SectionSpec[], locales: number): void {
    const seen = newSeen();
    for (let i = 0; i < sections.length; i += 1) {
        const section = sections[i];
        if (section === undefined) {
            continue;
        }
        const key = `tables.sections[${i}]`;
        checkName(collector, seen, section.key, `${key}.key`);

        const identifier = sectionIdentifier(section.key);
        if (seen.identifiers.has(identifier)) {
            collector.error(`${key}.key`, "identifier-collision");
        } else {
            seen.identifiers.add(identifier);
        }

        // The page a preview has to land a reader on, and a value the client
        // navigates to. It is checked as a route pattern for the same reason a
        // route's path is: `//evil.example` is a host, not a path.
        if (!section.site_path.startsWith("/")) {
            collector.error(`${key}.site_path`, "path-not-absolute");
        } else if (!kRoutePattern.test(section.site_path)) {
            collector.error(`${key}.site_path`, "path-not-a-route-pattern");
        }

        const fieldKeys = new Set<string>();
        for (let f = 0; f < section.fields.length; f += 1) {
            const field = section.fields[f];
            if (field === undefined) {
                continue;
            }
            const at = `${key}.fields[${f}]`;
            if (field.key.length === 0) {
                collector.error(`${at}.key`, "empty");
            } else if (!kFieldName.test(field.key)) {
                collector.error(`${at}.key`, "not-spellable");
            } else if (fieldKeys.has(field.key)) {
                collector.error(`${at}.key`, "duplicate-name");
            } else {
                fieldKeys.add(field.key);
            }

            collector.name(field.type, `${at}.type`);
            checkLabels(collector, field.labels, locales, `${at}.labels`);

            if (field.max_code_points < 0) {
                collector.error(`${at}.max_code_points`, "out-of-range");
            }

            const choices = new Set<string>();
            for (let c = 0; c < field.choices.length; c += 1) {
                const choice = field.choices[c];
                if (choice === undefined) {
                    continue;
                }
                // A choice is a STORED value rather than a name this generator
                // spells, so it is held to what a string reaching the file must
                // be and to nothing narrower: an application whose options are
                // written in its own script is not a malformed application.
                if (choice.length === 0) {
                    collector.error(`${at}.choices[${c}]`, "empty");
                } else if (kNotPlainText.test(choice)) {
                    collector.error(`${at}.choices[${c}]`, "not-plain-text");
                } else if (choices.has(choice)) {
                    collector.error(`${at}.choices[${c}]`, "duplicate-name");
                } else {
                    choices.add(choice);
                }
            }
        }

        const slots = new Set<string>();
        for (let m = 0; m < section.images.length; m += 1) {
            const image = section.images[m];
            if (image === undefined) {
                continue;
            }
            const at = `${key}.images[${m}]`;
            collector.name(image.slot, `${at}.slot`);
            if (slots.has(image.slot)) {
                collector.error(`${at}.slot`, "duplicate-name");
            } else {
                slots.add(image.slot);
            }
            checkLabels(collector, image.labels, locales, `${at}.labels`);
            if (image.min_width < 0 || image.min_height < 0) {
                collector.error(at, "out-of-range");
            }
            if (image.aspect !== null && (image.aspect.num <= 0 || image.aspect.den <= 0)) {
                collector.error(`${at}.aspect`, "not-positive");
            }
        }
    }
}

function checkTopics(
    collector: Collector,
    topics: readonly TopicSpec[],
    permissions: ReadonlySet<string>,
): void {
    const seen = newSeen();
    const words = new Set<string>();
    for (let i = 0; i < topics.length; i += 1) {
        const topic = topics[i];
        if (topic === undefined) {
            continue;
        }
        const key = `tables.topics[${i}]`;
        checkName(collector, seen, topic.key, `${key}.key`);
        checkValue(collector, seen, topic.code, `${key}.code`);

        const identifier = topicIdentifier(topic.key);
        if (seen.identifiers.has(identifier)) {
            collector.error(`${key}.key`, "identifier-collision");
        } else {
            seen.identifiers.add(identifier);
        }

        // Checked once per distinct word rather than once per row: these are
        // anvil's vocabulary, so the table repeats a handful of them, and the
        // key a problem is reported against is still the field it is in.
        const word = (value: string, at: string): void => {
            if (words.has(value)) {
                return;
            }
            words.add(value);
            collector.name(value, at);
        };
        word(topic.fanout, `${key}.fanout`);
        word(topic.scope, `${key}.scope`);
        for (let c = 0; c < topic.default_channels.length; c += 1) {
            const channel = topic.default_channels[c];
            if (channel !== undefined) {
                word(channel, `${key}.default_channels[${c}]`);
            }
        }

        for (let p = 0; p < topic.perms.length; p += 1) {
            const perm = topic.perms[p];
            if (perm !== undefined && !permissions.has(perm)) {
                collector.error(`${key}.perms[${p}]`, "unknown-permission");
            }
        }

        // anvil DERIVES visibility from the permission set — a topic requiring
        // nothing is public and any other is a holder's — so a descriptor where
        // the two disagree is not anvil's output. It is refused rather than
        // reconciled, and in both directions: `public` with a permission is a key
        // emitted into a bundle that the permission was supposed to gate, which
        // is the failure §4.1 exists to stop, and `holder` with none withholds a
        // key nothing protects, which reads as a gate that is not there.
        const gated = topic.perms.length !== 0;
        if (gated !== (topic.visibility !== "public")) {
            collector.error(`${key}.visibility`, "visibility-contradicts-perms");
        }

        if (topic.coalesce_window_s < 0) {
            collector.error(`${key}.coalesce_window_s`, "out-of-range");
        }
        if (topic.retention_days <= 0) {
            collector.error(`${key}.retention_days`, "not-positive");
        }
    }
}

function checkEvents(collector: Collector, events: readonly EventSpec[]): void {
    const seen = newSeen();
    const classes = new Set<string>();
    for (let i = 0; i < events.length; i += 1) {
        const event = events[i];
        if (event === undefined) {
            continue;
        }
        const key = `tables.events[${i}]`;
        checkName(collector, seen, event.name, `${key}.name`);
        checkValue(collector, seen, event.code, `${key}.code`);

        const identifier = eventIdentifier(event.name);
        if (seen.identifiers.has(identifier)) {
            collector.error(`${key}.name`, "identifier-collision");
        } else {
            seen.identifiers.add(identifier);
        }

        if (!classes.has(event.class)) {
            collector.name(event.class, `${key}.class`);
            classes.add(event.class);
        }

        const names = new Set<string>();
        for (let d = 0; d < event.dimensions.length; d += 1) {
            const dimension = event.dimensions[d];
            if (dimension === undefined) {
                continue;
            }
            const at = `${key}.dimensions[${d}]`;
            collector.name(dimension.name, `${at}.name`);
            if (names.has(dimension.name)) {
                collector.error(`${at}.name`, "duplicate-name");
            } else {
                names.add(dimension.name);
            }

            // The row stores the INDEX into this set, so a duplicate is two
            // names for one stored number and a value outside it is a row the
            // ingest path drops.
            const values = new Set<string>();
            for (let v = 0; v < dimension.values.length; v += 1) {
                const value = dimension.values[v];
                if (value === undefined) {
                    continue;
                }
                if (value.length === 0) {
                    collector.error(`${at}.values[${v}]`, "empty");
                } else if (kNotPlainText.test(value)) {
                    collector.error(`${at}.values[${v}]`, "not-plain-text");
                } else if (values.has(value)) {
                    collector.error(`${at}.values[${v}]`, "duplicate-name");
                } else {
                    values.add(value);
                }
            }
        }
    }
}

function checkMedia(collector: Collector, media: MediaTable): void {
    collector.name(media.default_role, "tables.media.default_role");

    const namespaces = new Set<string>();
    for (let i = 0; i < media.namespaces.length; i += 1) {
        const namespace = media.namespaces[i];
        if (namespace === undefined) {
            continue;
        }
        const key = `tables.media.namespaces[${i}]`;
        collector.name(namespace.ns, `${key}.ns`);
        if (namespaces.has(namespace.ns)) {
            collector.error(`${key}.ns`, "duplicate-name");
        } else {
            namespaces.add(namespace.ns);
        }

        // A namespace that accepts nothing is a namespace nothing can be
        // uploaded to, which is an emitter that forgot rather than a policy: the
        // accept list exists so the client's check and the server's are one
        // list, and an empty one makes the client's refuse everything.
        if (namespace.accepts.length === 0) {
            collector.error(`${key}.accepts`, "empty");
        }
        const accepted = new Set<string>();
        for (let a = 0; a < namespace.accepts.length; a += 1) {
            const type = namespace.accepts[a];
            if (type === undefined) {
                continue;
            }
            const at = `${key}.accepts[${a}]`;
            // `type/subtype`, lowercase, with no parameters. It reaches an
            // `accept` attribute and a comparison against `File.type`, which is
            // the browser's lowercase essence string — so a value with a
            // parameter or a capital never matches the thing it is checked
            // against, and the upload is refused for a reason nobody can see.
            if (!kMediaType.test(type)) {
                collector.error(at, "not-a-media-type");
            }
            if (accepted.has(type)) {
                collector.error(at, "duplicate-name");
            } else {
                accepted.add(type);
            }
        }

        const roles = new Set<string>();
        for (let r = 0; r < namespace.roles.length; r += 1) {
            const role = namespace.roles[r];
            if (role === undefined) {
                continue;
            }
            const at = `${key}.roles[${r}]`;
            collector.name(role.role, `${at}.role`);
            if (roles.has(role.role)) {
                collector.error(`${at}.role`, "duplicate-name");
            } else {
                roles.add(role.role);
            }
            if (role.width <= 0) {
                collector.error(`${at}.width`, "not-positive");
            }
        }

        // The role a request with no role segment resolves to — so a namespace
        // that does not serve it is one where forgetting the segment is a 404
        // rather than a smaller image, and the caller finds out in production.
        if (!roles.has(media.default_role)) {
            collector.error(`${key}.roles`, "unknown-media-role");
        }
    }
}

function checkRoutes(collector: Collector, tables: Tables): void {
    const permissions = new Set(tables.permissions.map((permission) => permission.name));
    const scopes = new Set(tables.capability_scopes.map((scope) => scope.name));
    const buckets = new Set(tables.rate_limits.map((bucket) => bucket.bucket));

    const seen = newSeen();
    const requiredScopes = new Set<string>();
    const namedBuckets = new Set<string>();

    for (let i = 0; i < tables.routes.length; i += 1) {
        const route = tables.routes[i];
        if (route === undefined) {
            continue;
        }
        const key = `tables.routes[${i}]`;
        checkName(collector, seen, route.id, `${key}.id`);

        const identifier = routeIdentifier(route.id);
        if (seen.identifiers.has(identifier)) {
            collector.error(`${key}.id`, "identifier-collision");
        } else {
            seen.identifiers.add(identifier);
        }

        pathParameters(collector, route.path, `${key}.path`);

        // `ANY` is not a method. It is a declaration that every method shares
        // one policy, and anvil emits it so that a client fails loudly on a
        // description that forgot to name one rather than defaulting to GET and
        // silently calling the wrong thing (`descriptor/route_description.h`).
        //
        // For a PUBLIC route the method is emitted as a value, so `ANY` is a
        // client that cannot call a route it can see: a generation failure, which
        // is where a thing an application must supply belongs. For a holder route
        // the method is not emitted at all — it arrives with the session — so the
        // failure cannot happen until run time, and this is the only place the
        // build can say so.
        if (route.method === "ANY") {
            if (route.visibility === "public") {
                collector.error(`${key}.method`, "unusable-method");
            } else {
                collector.warn(`${key}.method`, "unusable-method");
            }
        }

        for (let p = 0; p < route.perms.length; p += 1) {
            const perm = route.perms[p];
            if (perm !== undefined && !permissions.has(perm)) {
                collector.error(`${key}.perms[${p}]`, "unknown-permission");
            }
        }

        if (route.capability.length !== 0) {
            if (scopes.has(route.capability)) {
                requiredScopes.add(route.capability);
            } else {
                collector.error(`${key}.capability`, "unknown-capability-scope");
            }
        }

        if (route.rate_limit.length !== 0) {
            if (buckets.has(route.rate_limit)) {
                namedBuckets.add(route.rate_limit);
            } else {
                collector.error(`${key}.rate_limit`, "unknown-rate-limit-bucket");
            }
        }

        if (route.response !== null) {
            // Two fields with one key is a body whose second value overwrites
            // the first in every JSON parser there is, and an emitted type with
            // a duplicate property does not compile — so it fails here, naming
            // the field, rather than in the consumer's build naming a line of
            // generated code.
            const fields = new Set<string>();
            for (let f = 0; f < route.response.fields.length; f += 1) {
                const field = route.response.fields[f];
                if (field === undefined) {
                    continue;
                }
                if (fields.has(field.name)) {
                    collector.error(`${key}.response.fields[${f}].name`, "duplicate-field");
                } else {
                    fields.add(field.name);
                }
            }
        }

        if (route.page !== null) {
            if (route.page.cursor.length === 0) {
                collector.error(`${key}.page.cursor`, "empty");
            } else if (!kFieldName.test(route.page.cursor)) {
                collector.error(`${key}.page.cursor`, "not-spellable");
            }
            if (route.page.limit_max <= 0) {
                collector.error(`${key}.page.limit_max`, "not-positive");
            } else if (route.page.limit_max > tables.limits.page_limit_max) {
                collector.error(`${key}.page.limit_max`, "above-maximum");
            }
        }
    }

    for (let i = 0; i < tables.capability_scopes.length; i += 1) {
        const scope = tables.capability_scopes[i];
        if (scope !== undefined && !requiredScopes.has(scope.name)) {
            collector.warn(`tables.capability_scopes[${i}].name`, "no-route-requires-it");
        }
    }

    for (let i = 0; i < tables.rate_limits.length; i += 1) {
        const bucket = tables.rate_limits[i];
        if (bucket !== undefined && !namedBuckets.has(bucket.bucket)) {
            collector.warn(`tables.rate_limits[${i}].bucket`, "no-route-names-it");
        }
    }
}

// --- the entry points -------------------------------------------------------

const kSha256 = /^[0-9a-f]{64}$/;

export function readDescriptor(
    source: unknown,
): Result<DescriptorReading, readonly DescriptorProblem[]> {
    const collector = new Collector();

    const root = collector.object(source, "");
    if (root === null) {
        return fail(collector.errors);
    }

    const format = collector.integer(root, "descriptor", "descriptor");
    if (format !== null && format !== kSupportedFormat) {
        collector.error("descriptor", "unsupported-format");
    }

    const emittedBy = collector.string(root, "emitted_by", "emitted_by");
    const hash = collector.string(root, "hash", "hash");
    if (hash !== null && !kSha256.test(hash)) {
        collector.error("hash", "not-a-sha256");
    }

    const app = collector.object(root["app"], "app");
    const appName = app === null ? null : collector.string(app, "name", "app.name");
    const appVersion = app === null ? null : collector.string(app, "version", "app.version");

    const rawTables = collector.object(root["tables"], "tables");
    if (rawTables === null) {
        return fail(collector.errors);
    }

    const errorCodes = readErrorCodes(collector, rawTables["error_codes"]);
    const reasons = readEnumerators(collector, rawTables["validation_reasons"], "tables.validation_reasons");
    const permissions = readPermissions(collector, rawTables["permissions"]);
    const locales = readLocales(collector, rawTables["locales"]);
    const routes = readRoutes(collector, rawTables["routes"]);
    const scopes = readCapabilityScopes(collector, rawTables["capability_scopes"]);
    const rateLimits = readRateLimits(collector, rawTables["rate_limits"]);
    const limits = readLimits(collector, rawTables["limits"]);
    const fieldTypes = readFieldTypes(collector, rawTables["field_types"]);
    const sections = readSections(collector, rawTables["sections"]);
    const topics = readTopics(collector, rawTables["topics"]);
    const events = readEvents(collector, rawTables["events"]);
    const media = readMedia(collector, rawTables["media"]);

    if (
        format === null ||
        emittedBy === null ||
        hash === null ||
        appName === null ||
        appVersion === null ||
        errorCodes === null ||
        reasons === null ||
        permissions === null ||
        locales === null ||
        routes === null ||
        scopes === null ||
        rateLimits === null ||
        limits === null ||
        fieldTypes === null ||
        sections === null ||
        topics === null ||
        events === null ||
        media === null ||
        collector.errors.length !== 0
    ) {
        return fail(collector.errors);
    }

    const tables: Tables = {
        error_codes: errorCodes,
        validation_reasons: reasons,
        permissions,
        locales,
        routes,
        capability_scopes: scopes,
        rate_limits: rateLimits,
        limits,
        field_types: fieldTypes,
        sections,
        topics,
        events,
        media,
    };

    checkErrorCodes(collector, tables.error_codes);
    checkEnumerators(collector, tables.validation_reasons, "tables.validation_reasons");
    checkPermissions(collector, tables.permissions);
    checkLocales(collector, tables.locales);
    checkCapabilityScopes(collector, tables.capability_scopes);
    checkRateLimits(collector, tables.rate_limits);
    checkLimits(collector, tables.limits);
    checkRoutes(collector, tables);
    checkFieldTypes(collector, tables.field_types);
    checkSections(collector, tables.sections, tables.locales.length);
    checkTopics(
        collector,
        tables.topics,
        new Set(tables.permissions.map((permission) => permission.name)),
    );
    checkEvents(collector, tables.events);
    checkMedia(collector, tables.media);

    if (collector.errors.length !== 0) {
        return fail(collector.errors);
    }

    const descriptor: Descriptor = {
        descriptor: format,
        emitted_by: emittedBy,
        app: { name: appName, version: appVersion },
        hash,
        tables,
    };
    return ok({ descriptor, warnings: collector.warnings });
}

// JSON.parse throws, and a file that is not JSON is an expected condition rather
// than a programmer error: it is whatever was on disk.
export function readDescriptorJson(
    text: string,
): Result<DescriptorReading, readonly DescriptorProblem[]> {
    let parsed: unknown;
    try {
        parsed = JSON.parse(text);
    } catch {
        return fail([{ key: "", issue: "not-json" }]);
    }
    return readDescriptor(parsed);
}
