// DO NOT EDIT. Generated by hammer codegen.
//
// Regenerate with:
//
//     hammer codegen --descriptor <descriptor.json> --out <dir>
//
// Descriptor format: 4
// Tables: sha256 f8ded797049128c3ffe4cedf4250939e91fc140be4a5ef75f697e691c5f38b7d
//
// Nothing above `tables` in the descriptor reaches this file, and the
// omission is the reason the hash covers `tables` and nothing else: an
// application's version changes on every release and changes no table, so a
// module carrying it would diff on every release and be regenerated for
// nothing. The hash answers the one question worth failing a build over —
// whether this client was generated from these tables.
//
// The module has no side effects and no default export, and every table is
// an individual `const`. A bundler can drop an export nothing references; it
// cannot drop one member of an object something imported.

// --- the client's provenance ------------------------------------------------

export const kDescriptorFormat = 4;

// Compared against the hash the session response carries. A mismatch is a
// stale bundle, and it is surfaced rather than acted on: an automatic reload
// discards whatever the user had typed, on the deploy most likely to be
// happening during working hours (docs/00-architecture.md §7.1).
export const kTablesHash = "f8ded797049128c3ffe4cedf4250939e91fc140be4a5ef75f697e691c5f38b7d";

// --- error codes ------------------------------------------------------------

// The wire names, unchanged. A second spelling would be a translation table
// in every bundle that decodes an envelope, a second copy of an enum that is
// append-only server-side, and a word on a screen that does not match the
// word in the log somebody is reading it against.
//
// `Unknown` is hammer's, and its shape is deliberate: anvil's enumerators are
// SCREAMING_SNAKE, so no code it appends can collide with it. A client that
// threw on a code added this morning would turn a deploy into an outage in
// every tab that was already open.
export type ErrorCode =
    | "UNAUTHENTICATED"
    | "FORBIDDEN"
    | "NOT_FOUND"
    | "CAPABILITY_REQUIRED"
    | "CAPABILITY_INVALID"
    | "VALIDATION_FAILED"
    | "CONFLICT"
    | "VERSION_MISMATCH"
    | "RATE_LIMITED"
    | "PAYLOAD_TOO_LARGE"
    | "UNSUPPORTED_MEDIA"
    | "SERVICE_UNAVAILABLE"
    | "INTERNAL"
    | "INSUFFICIENT_STORAGE"
    | "Unknown";

// The member that is not a failure, and therefore not a member of the union
// above: an application would otherwise owe a sentence for a case no error
// surface can reach.
export const kErrorCodeOk = "OK";

// Every member with the value anvil stores, the success member included. The
// decode needs the set of names; the numbers are here because anvil keeps them
// in audit rows that are read back long after the deploy that wrote them.
export const kErrorCodeValues = {
    OK: 0,
    UNAUTHENTICATED: 1,
    FORBIDDEN: 2,
    NOT_FOUND: 3,
    CAPABILITY_REQUIRED: 4,
    CAPABILITY_INVALID: 5,
    VALIDATION_FAILED: 6,
    CONFLICT: 7,
    VERSION_MISMATCH: 8,
    RATE_LIMITED: 9,
    PAYLOAD_TOO_LARGE: 10,
    UNSUPPORTED_MEDIA: 11,
    SERVICE_UNAVAILABLE: 12,
    INTERNAL: 13,
    INSUFFICIENT_STORAGE: 14,
} as const;

// The bound the decode can state, because the enum is append-only.
export const kErrorCodeMaxValue = 14;

// Carried for the contract suite rather than for the run time: hammer branches
// on the code, and this is what asserts the server still maps it the way it did.
export const kErrorCodeHttpStatus = {
    OK: 200,
    UNAUTHENTICATED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CAPABILITY_REQUIRED: 428,
    CAPABILITY_INVALID: 403,
    VALIDATION_FAILED: 400,
    CONFLICT: 409,
    VERSION_MISMATCH: 409,
    RATE_LIMITED: 429,
    PAYLOAD_TOO_LARGE: 413,
    UNSUPPORTED_MEDIA: 415,
    SERVICE_UNAVAILABLE: 503,
    INTERNAL: 500,
    INSUFFICIENT_STORAGE: 507,
} as const;

// The codes the stealth filter rewrites to a 404. A client needs them to know
// that a not-found answer on a stealth route is not evidence of anything — and
// that rendering a denial there rebuilds the oracle the server removed.
export const kStealthHiddenErrorCodes = [
    "UNAUTHENTICATED",
    "FORBIDDEN",
    "CAPABILITY_REQUIRED",
    "CAPABILITY_INVALID",
] as const;

// --- validation reasons -----------------------------------------------------

// anvil names the reason a field failed and never the sentence. The map from a
// reason to words is `Record<ValidationReason, string>` in the application, so a
// reason added server-side is a compile error in every client until somebody
// writes them — the alternative is a fallback string, and a fallback string is
// how a wire enumerator reaches a user in an interface that is otherwise
// entirely in Arabic.
//
// `Unknown` is here for the reason it is in `ErrorCode`, and it is the
// member that makes the compile error above safe to rely on. `Reason` is
// append-only server-side too, so a deploy can answer an open tab with a
// reason its bundle predates. The alternative to a member is dropping the
// field from the map, which is a form that refuses to submit with nothing
// marked on it — and that is worse than a sentence that is too general.
export type ValidationReason =
    | "REQUIRED"
    | "TOO_SHORT"
    | "TOO_LONG"
    | "BAD_FORMAT"
    | "BAD_CHARSET"
    | "OUT_OF_RANGE"
    | "NOT_ALLOWED"
    | "BAD_CHECKSUM"
    | "WEAK"
    | "BREACHED"
    | "Unknown";

export const kValidationReasonValues = {
    OK: 0,
    REQUIRED: 1,
    TOO_SHORT: 2,
    TOO_LONG: 3,
    BAD_FORMAT: 4,
    BAD_CHARSET: 5,
    OUT_OF_RANGE: 6,
    NOT_ALLOWED: 7,
    BAD_CHECKSUM: 8,
    WEAK: 9,
    BREACHED: 10,
} as const;

// --- permissions ------------------------------------------------------------

// One `const` per bit and no table of names. A membership test is
// `permissions.has(kPermContentRead)` — a number against sixteen bytes — and the
// union below is erased, so a bundle carries no permission name at all.
//
// An application that has to SHOW a permission's name writes it as
// `Record<Permission, string>`, which is copy, and copy is the application's
// (docs/01-seams.md §13). It is then total by type: a permission added
// server-side is a compile error until it has a word.
//
// Bit indices are stored in access tokens and in the user document and are
// never renumbered. A renumber is a silent regrant of authority, and it is not
// something this side can check.
export type Permission =
    | "dashboard"
    | "applications"
    | "form_maker"
    | "teams"
    | "content"
    | "gallery"
    | "users"
    | "media_upload"
    | "form_read";

export const kPermDashboard = 0;
export const kPermApplications = 1;
export const kPermFormMaker = 2;
export const kPermTeams = 3;
export const kPermContent = 4;
export const kPermGallery = 5;
export const kPermUsers = 6;
export const kPermMediaUpload = 16;
export const kPermFormRead = 17;

// The one place a table of names is unavoidable, and it is its own `const` for
// exactly that reason.
//
// anvil sends a holder's permissions on the session response as NAMES in bit
// order rather than as a mask — `for_each_name` skips the reserved gaps between
// an application's blocks, so a bit nothing names never reaches a client as a
// control that authorises nothing — and nothing can turn a name back into a bit
// without the map. `SessionStore` takes it, and a chunk that decodes no session
// references it and therefore ships none of these names.
//
// That is the whole reason it is not a member of `kApiTables`: putting it there
// would put every permission name into any bundle that constructs a client,
// including the one an anonymous visitor downloads.
export const kPermissionBits = {
    dashboard: kPermDashboard,
    applications: kPermApplications,
    form_maker: kPermFormMaker,
    teams: kPermTeams,
    content: kPermContent,
    gallery: kPermGallery,
    users: kPermUsers,
    media_upload: kPermMediaUpload,
    form_read: kPermFormRead,
} as const;

// --- locales ----------------------------------------------------------------

// In the server's order, which is persisted and append-only: anvil stores a
// locale as a one-byte index into this table. Never sorted, never renumbered,
// and index 0 means nothing in particular.
//
// `collation` is carried so a client-side sort agrees with the server's. They
// are otherwise two different orderings of the same rows, and the disagreement
// shows up exactly at a page boundary — where a row appears twice, or never.
export type Locale =
    | "en";

export const kLocales = [
    { tag: "en", collation: "en", rtl: false },
] as const;

// --- capability scopes ------------------------------------------------------

// A route declaring a scope takes a `Capability<Scope>` in its parameters, and
// the only producer of one is the call that mints it — so the requirement is
// discharged by the compiler rather than by a reviewer.
//
// No TTL here. A scope declares whether redemption burns the token; how long a
// particular token lives is a property of that token, set where it is minted.
export type CapabilityScope = never;

export const kCapabilityScopeValues = {} as const;

// Whether redemption burns the token. A call carrying a single-use capability
// is never auto-retried: the server consumed it whether or not the response
// arrived, so a retry gets CAPABILITY_INVALID and reports a failure for an
// operation that succeeded. The recovery is a re-read, not a retry.
export const kCapabilitySingleUse = {} as const;

// --- rate limits ------------------------------------------------------------

// Advisory, and not the limit — the server's is. The client's copy exists so an
// interface does not spend a user's budget on its own retries and then present
// them with a lockout they did not cause.
//
// A 429 holds back the whole bucket rather than the one call. Retrying the
// other nine while one waits is how a rate limit becomes a lockout.
export type RateLimitBucket =
    | "login"
    | "login-acct"
    | "refresh"
    | "closed"
    | "apply"
    | "submit"
    | "visit"
    | "staff-write"
    | "media";

export const kRateLimits = {
    login: { windowMs: 60000, maxEvents: 20 },
    "login-acct": { windowMs: 900000, maxEvents: 10 },
    refresh: { windowMs: 60000, maxEvents: 60 },
    closed: { windowMs: 3600000, maxEvents: 1 },
    apply: { windowMs: 600000, maxEvents: 5 },
    submit: { windowMs: 600000, maxEvents: 10 },
    visit: { windowMs: 60000, maxEvents: 30 },
    "staff-write": { windowMs: 60000, maxEvents: 120 },
    media: { windowMs: 60000, maxEvents: 30 },
} as const;

// --- limits -----------------------------------------------------------------

// Individual constants, and the unit is in the name: a bound whose unit lives
// in a comment is a bound that gets read as the other one. A byte cap is bytes
// and a text bound is code points, and the two are never conflated.
//
// The upload cap is checked against `file.size` before the first byte is sent.
// It is not the enforcement — anvil enforces during the stream, because a
// client-side check is a check an attacker skips.
export const kUploadMaxBytes = 26214400;
export const kBodyMaxBytes = 262144;
export const kPageLimitMax = 100;

// The image edit recipe's bounds, as the server enforces them. `hammer/edit`
// validates a recipe against exactly these, so a person hitting the stroke cap
// learns it while drawing rather than after pressing save. The two edges are
// the server's widest and narrowest variant widths — numbers, not addresses.
export const kEditLimits = {
    maxStrokes: 64,
    maxPoints: 4096,
    maxEdgePx: 1600,
    minEdgePx: 320,
} as const;

// --- routes -----------------------------------------------------------------

// Every route's SHAPE is a type, and types are erased: a shape cannot leak
// because at run time it does not exist. What is emitted as a value is decided
// by visibility, and only there.
export type RouteId =
    | "auth.salt"
    | "auth.login"
    | "auth.refresh"
    | "auth.logout"
    | "auth.password"
    | "session.current"
    | "identity.me"
    | "site.get"
    | "teams.list"
    | "applications.apply"
    | "forms.public"
    | "forms.submit"
    | "visits.record"
    | "media.object"
    | "dashboard.get"
    | "audit.list"
    | "applications.list"
    | "applications.update"
    | "applications.delete"
    | "teams.create"
    | "teams.update"
    | "teams.delete"
    | "members.list"
    | "members.add"
    | "members.update"
    | "members.remove"
    | "teams.reorder"
    | "sections.list"
    | "sections.publish"
    | "gallery.list"
    | "gallery.add"
    | "gallery.remove"
    | "gallery.reorder"
    | "media.upload"
    | "forms.list"
    | "forms.create"
    | "forms.update"
    | "forms.delete"
    | "responses.list"
    | "responses.delete"
    | "responses.export"
    | "staff.list"
    | "staff.create"
    | "staff.update"
    | "staff.disable";

// Reachable with no credential at all — the paths below are values.
export type PublicRouteId =
    | "auth.salt"
    | "auth.login"
    | "auth.refresh"
    | "session.current"
    | "site.get"
    | "teams.list"
    | "applications.apply"
    | "forms.public"
    | "forms.submit"
    | "visits.record"
    | "media.object";

// Everything else. The id is here, the path is not: it arrives with the session,
// filtered by the server to what this holder's permissions actually reach, so a
// content editor never learns the addresses of the routes above them.
export type HolderRouteId =
    | "auth.logout"
    | "auth.password"
    | "identity.me"
    | "dashboard.get"
    | "audit.list"
    | "applications.list"
    | "applications.update"
    | "applications.delete"
    | "teams.create"
    | "teams.update"
    | "teams.delete"
    | "members.list"
    | "members.add"
    | "members.update"
    | "members.remove"
    | "teams.reorder"
    | "sections.list"
    | "sections.publish"
    | "gallery.list"
    | "gallery.add"
    | "gallery.remove"
    | "gallery.reorder"
    | "media.upload"
    | "forms.list"
    | "forms.create"
    | "forms.update"
    | "forms.delete"
    | "responses.list"
    | "responses.delete"
    | "responses.export"
    | "staff.list"
    | "staff.create"
    | "staff.update"
    | "staff.disable";

// The path parameters of each route, whatever its visibility. A holder route's
// parameters are as safe to emit as its id: this is a type, and it is gone by
// the time a bundle exists.
export type RouteParams = {
    readonly "auth.salt": Record<string, never>;
    readonly "auth.login": Record<string, never>;
    readonly "auth.refresh": Record<string, never>;
    readonly "auth.logout": Record<string, never>;
    readonly "auth.password": Record<string, never>;
    readonly "session.current": Record<string, never>;
    readonly "identity.me": Record<string, never>;
    readonly "site.get": Record<string, never>;
    readonly "teams.list": Record<string, never>;
    readonly "applications.apply": Record<string, never>;
    readonly "forms.public": { readonly id: string };
    readonly "forms.submit": { readonly id: string };
    readonly "visits.record": Record<string, never>;
    readonly "media.object": { readonly ns: string; readonly id: string; readonly role: string };
    readonly "dashboard.get": Record<string, never>;
    readonly "audit.list": Record<string, never>;
    readonly "applications.list": Record<string, never>;
    readonly "applications.update": { readonly id: string };
    readonly "applications.delete": { readonly id: string };
    readonly "teams.create": Record<string, never>;
    readonly "teams.update": { readonly id: string };
    readonly "teams.delete": { readonly id: string };
    readonly "members.list": { readonly id: string };
    readonly "members.add": { readonly id: string };
    readonly "members.update": { readonly id: string; readonly member: string };
    readonly "members.remove": { readonly id: string; readonly member: string };
    readonly "teams.reorder": Record<string, never>;
    readonly "sections.list": Record<string, never>;
    readonly "sections.publish": { readonly key: string };
    readonly "gallery.list": { readonly kind: string };
    readonly "gallery.add": { readonly kind: string };
    readonly "gallery.remove": { readonly kind: string; readonly id: string };
    readonly "gallery.reorder": { readonly kind: string };
    readonly "media.upload": Record<string, never>;
    readonly "forms.list": Record<string, never>;
    readonly "forms.create": Record<string, never>;
    readonly "forms.update": { readonly id: string };
    readonly "forms.delete": { readonly id: string };
    readonly "responses.list": { readonly id: string };
    readonly "responses.delete": { readonly id: string; readonly response: string };
    readonly "responses.export": { readonly id: string };
    readonly "staff.list": Record<string, never>;
    readonly "staff.create": Record<string, never>;
    readonly "staff.update": { readonly id: string };
    readonly "staff.disable": { readonly id: string };
};

// The capability scope each route consumes, or null.
export type RouteCapability = {
    readonly "auth.salt": null;
    readonly "auth.login": null;
    readonly "auth.refresh": null;
    readonly "auth.logout": null;
    readonly "auth.password": null;
    readonly "session.current": null;
    readonly "identity.me": null;
    readonly "site.get": null;
    readonly "teams.list": null;
    readonly "applications.apply": null;
    readonly "forms.public": null;
    readonly "forms.submit": null;
    readonly "visits.record": null;
    readonly "media.object": null;
    readonly "dashboard.get": null;
    readonly "audit.list": null;
    readonly "applications.list": null;
    readonly "applications.update": null;
    readonly "applications.delete": null;
    readonly "teams.create": null;
    readonly "teams.update": null;
    readonly "teams.delete": null;
    readonly "members.list": null;
    readonly "members.add": null;
    readonly "members.update": null;
    readonly "members.remove": null;
    readonly "teams.reorder": null;
    readonly "sections.list": null;
    readonly "sections.publish": null;
    readonly "gallery.list": null;
    readonly "gallery.add": null;
    readonly "gallery.remove": null;
    readonly "gallery.reorder": null;
    readonly "media.upload": null;
    readonly "forms.list": null;
    readonly "forms.create": null;
    readonly "forms.update": null;
    readonly "forms.delete": null;
    readonly "responses.list": null;
    readonly "responses.delete": null;
    readonly "responses.export": null;
    readonly "staff.list": null;
    readonly "staff.create": null;
    readonly "staff.update": null;
    readonly "staff.disable": null;
};

// What a route answers with, for the routes anvil DECLARED an answer for.
//
// These are not a guess at the handler. anvil writes a described body through a
// response binder, where writing a key that is not next, writing one of the
// wrong type or stopping before the last field are compile errors on the SERVER
// — so the schema is a description of the bytes rather than a claim about them,
// which is the only condition under which generating types from one is better
// than generating none. A type nothing enforces is a lie that type-checks.
//
// A route with no declaration is absent here and resolves to `unknown`, which
// forces its call sites to narrow loudly rather than inherit that lie. Declare
// one in your application the way this interface was augmented before anvil
// emitted any of them:
//
//     declare module "./hammer.generated.js" {
//         interface RouteResponses {
//             "content.get": { readonly id: string };
//         }
//     }
export interface RouteResponses {}

export type ResponseOf<Id extends RouteId> = Id extends keyof RouteResponses
    ? RouteResponses[Id]
    : unknown;

// One `const` per route. A screen that calls two routes ships two, and a bundle
// an anonymous visitor can fetch carries neither the ids nor the facts of the
// rest — which is a property of the emission shape, not of the bundler's
// configuration.
//
// `method` and `path` are null for a holder route in every bundle. There is no
// table of them anywhere in this file, deliberately: an aggregate would put
// every route's facts into any bundle that touched one of them.
export const routeAuthSalt = {
    id: "auth.salt",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/auth/salt",
    perms: [],
    capability: null,
    rateLimit: "login",
    idempotent: true,
    page: null,
} as const;

export const routeAuthLogin = {
    id: "auth.login",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/auth/login",
    perms: [],
    capability: null,
    rateLimit: "login",
    idempotent: false,
    page: null,
} as const;

export const routeAuthRefresh = {
    id: "auth.refresh",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/auth/refresh",
    perms: [],
    capability: null,
    rateLimit: "refresh",
    idempotent: false,
    page: null,
} as const;

export const routeAuthLogout = {
    id: "auth.logout",
    access: "authenticated",
    visibility: "holder",
    method: null,
    path: null,
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeAuthPassword = {
    id: "auth.password",
    access: "authenticated",
    visibility: "holder",
    method: null,
    path: null,
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: false,
    page: null,
} as const;

export const routeSessionCurrent = {
    id: "session.current",
    access: "authenticated",
    visibility: "public",
    method: "GET",
    path: "/api/session",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeIdentityMe = {
    id: "identity.me",
    access: "authenticated",
    visibility: "holder",
    method: null,
    path: null,
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeSiteGet = {
    id: "site.get",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/api/site",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeTeamsList = {
    id: "teams.list",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/api/teams",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeApplicationsApply = {
    id: "applications.apply",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/applications",
    perms: [],
    capability: null,
    rateLimit: "apply",
    idempotent: false,
    page: null,
} as const;

export const routeFormsPublic = {
    id: "forms.public",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/api/forms/{id}",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeFormsSubmit = {
    id: "forms.submit",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/forms/{id}/responses",
    perms: [],
    capability: null,
    rateLimit: "submit",
    idempotent: false,
    page: null,
} as const;

export const routeVisitsRecord = {
    id: "visits.record",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/visits",
    perms: [],
    capability: null,
    rateLimit: "visit",
    idempotent: false,
    page: null,
} as const;

export const routeMediaObject = {
    id: "media.object",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/media/{ns}/{id}/{role}",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeDashboardGet = {
    id: "dashboard.get",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermDashboard],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeAuditList = {
    id: "audit.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermUsers],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: { cursor: "_id", limitMax: 100 },
} as const;

export const routeApplicationsList = {
    id: "applications.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermApplications],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: { cursor: "_id", limitMax: 100 },
} as const;

export const routeApplicationsUpdate = {
    id: "applications.update",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermApplications],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeApplicationsDelete = {
    id: "applications.delete",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermApplications],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeTeamsCreate = {
    id: "teams.create",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeTeamsUpdate = {
    id: "teams.update",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeTeamsDelete = {
    id: "teams.delete",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeMembersList = {
    id: "members.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeMembersAdd = {
    id: "members.add",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeMembersUpdate = {
    id: "members.update",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeMembersRemove = {
    id: "members.remove",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeTeamsReorder = {
    id: "teams.reorder",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermTeams],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeSectionsList = {
    id: "sections.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermContent],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeSectionsPublish = {
    id: "sections.publish",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermContent],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeGalleryList = {
    id: "gallery.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermGallery],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeGalleryAdd = {
    id: "gallery.add",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermGallery],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeGalleryRemove = {
    id: "gallery.remove",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermGallery],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeGalleryReorder = {
    id: "gallery.reorder",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermGallery],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeMediaUpload = {
    id: "media.upload",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermMediaUpload],
    capability: null,
    rateLimit: "media",
    idempotent: false,
    page: null,
} as const;

export const routeFormsList = {
    id: "forms.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermFormMaker],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeFormsCreate = {
    id: "forms.create",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermFormMaker],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeFormsUpdate = {
    id: "forms.update",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermFormMaker],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeFormsDelete = {
    id: "forms.delete",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermFormMaker],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeResponsesList = {
    id: "responses.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermFormRead],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: { cursor: "_id", limitMax: 50 },
} as const;

export const routeResponsesDelete = {
    id: "responses.delete",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermFormMaker],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

export const routeResponsesExport = {
    id: "responses.export",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermFormRead],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeStaffList = {
    id: "staff.list",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermUsers],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeStaffCreate = {
    id: "staff.create",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermUsers],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeStaffUpdate = {
    id: "staff.update",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermUsers],
    capability: null,
    rateLimit: "staff-write",
    idempotent: false,
    page: null,
} as const;

export const routeStaffDisable = {
    id: "staff.disable",
    access: "guarded",
    visibility: "holder",
    method: null,
    path: null,
    perms: [kPermUsers],
    capability: null,
    rateLimit: "staff-write",
    idempotent: true,
    page: null,
} as const;

// The public tier as one table, for a client that resolves an id at run time.
// Only this tier can be a table at all — a holder route has no path to put in
// one — and a consumer that wants the whole table pays for the whole table,
// which is the choice being offered rather than made for them.
export const publicRoutes = {
    "auth.salt": routeAuthSalt,
    "auth.login": routeAuthLogin,
    "auth.refresh": routeAuthRefresh,
    "session.current": routeSessionCurrent,
    "site.get": routeSiteGet,
    "teams.list": routeTeamsList,
    "applications.apply": routeApplicationsApply,
    "forms.public": routeFormsPublic,
    "forms.submit": routeFormsSubmit,
    "visits.record": routeVisitsRecord,
    "media.object": routeMediaObject,
} as const;

// --- the client -------------------------------------------------------------

// What this client knows, as ONE type parameter rather than four. Every call is
// then typed by the route `const` it names: a route that does not exist cannot
// be spelled, a parameter cannot be omitted, and a route declaring a capability
// scope will not compile without a `Capability` for that scope.
//
// A route with no `RouteResponses` declaration resolves to `unknown` here, which
// forces its call sites to narrow loudly rather than inherit a lie.
//
// `hash` is what PAIRS this type with the tables below it. It is a literal type,
// so two applications with two generated modules cannot cross them: the tables
// carry one descriptor's hash and the type demands that descriptor's hash, and a
// mismatch is a compile error at `createClient` rather than a client decoding one
// server's vocabulary against another's. Two modules generated from the SAME
// descriptor pair freely, which is correct — they are the same tables.
//
//     import { createClient } from "hammer/wire";
//     import { kApiTables, routeAuthRefresh } from "./hammer.generated.js";
//     import type { Api } from "./hammer.generated.js";
//
//     const client = createClient<Api>({
//         api: kApiTables,
//         refreshRoute: routeAuthRefresh,
//         origin: { pageOrigin: location.origin, apiOrigin, site: null },
//         fetch: window.fetch.bind(window),
//         session: sessions.source,
//     });
export type Api = {
    readonly params: RouteParams;
    readonly responses: { readonly [Id in RouteId]: ResponseOf<Id> };
    readonly code: ErrorCode;
    readonly reason: ValidationReason;
    readonly hash: typeof kTablesHash;
};

// One descriptor's tables, as one member. They are generated together and they
// are handed over together, so the set a client decodes with is the set whose
// hash is checked against the server's.
//
// An object literal over the constants above — no call and no import — so a
// bundle that references none of this still drops all of it, and this module
// still depends on nothing.
//
// `hash` is the sixth member and it is not decoded with: it is the descriptor
// this set came from, as a value, so that `Api` above can demand the same one.
// Without it the pairing was a CONVENTION — both names come out of one file — and
// a convention holds until an application has two generated modules.
//
// `refreshRoute` is deliberately NOT in here. The descriptor does not say which
// route a refresh goes to, so putting one in would be this generator guessing at
// an id; the application names it, and naming it is one line.
export const kApiTables = {
    codes: kErrorCodeValues,
    reasons: kValidationReasonValues,
    rateLimits: kRateLimits,
    singleUse: kCapabilitySingleUse,
    bodyMaxBytes: kBodyMaxBytes,
    hash: kTablesHash,
} as const;

// --- field types ------------------------------------------------------------

// What a form definition's fields may declare. The renderer is hammer's and
// the table is the application's: a field type is machinery — a control, a
// validation rule, an answer shape — and the particular set an application
// declares is not.
export type FieldTypeName =
    | "TEXT_SHORT"
    | "TEXT_LONG"
    | "EMAIL"
    | "PHONE"
    | "SELECT_SINGLE";

// The JSON shape an answer arrives in and is read back as. A PII type has
// `null` here rather than a kind: its value is never echoed back, so a
// renderer told `"text"` renders a control for a value that has silently
// emptied itself.
export type AnswerKind =
    | "text"
    | "choice";

// One table rather than one `const` per type, because the lookup is by the
// `code` a definition carries at run time: every consumer that renders a form
// resolves a type it was handed rather than one it spelled, so there is no
// bundle in which a subset of this table is the useful part.
//
// `defaultCodePoints` is CODE POINTS, as its name says, and it is the number
// the server checks against. A client enforcing it in UTF-16 code units
// refuses text the server would have accepted, which for any non-Latin script
// is most of it.
//
// The flags are named booleans and not the byte anvil stores, for the reason
// everything else here is a name: a client carrying a copy of a bitmask is a
// client carrying a copy of an enum.
export const kFieldTypes = {
    TEXT_SHORT: {
        code: 0,
        pii: false,
        answer: "text",
        defaultCodePoints: 200,
        flags: {
            options: false,
            attachment: false,
            ranged: false,
            codePointCapped: true,
            multiLine: false,
            multiSelect: false,
        },
    },
    TEXT_LONG: {
        code: 1,
        pii: false,
        answer: "text",
        defaultCodePoints: 4000,
        flags: {
            options: false,
            attachment: false,
            ranged: false,
            codePointCapped: true,
            multiLine: true,
            multiSelect: false,
        },
    },
    EMAIL: {
        code: 2,
        pii: false,
        answer: "text",
        defaultCodePoints: 0,
        flags: {
            options: false,
            attachment: false,
            ranged: false,
            codePointCapped: false,
            multiLine: false,
            multiSelect: false,
        },
    },
    PHONE: {
        code: 3,
        pii: false,
        answer: "text",
        defaultCodePoints: 32,
        flags: {
            options: false,
            attachment: false,
            ranged: false,
            codePointCapped: true,
            multiLine: false,
            multiSelect: false,
        },
    },
    SELECT_SINGLE: {
        code: 4,
        pii: false,
        answer: "choice",
        defaultCodePoints: 0,
        flags: {
            options: true,
            attachment: false,
            ranged: false,
            codePointCapped: false,
            multiLine: false,
            multiSelect: false,
        },
    },
} as const;

// --- sections ---------------------------------------------------------------

// The editable surface: what a section holds, what bounds each field is under,
// and which image slots it offers.
//
// `labels` is the one place the descriptor carries words a person reads, and it
// is not an exception to the rule that hammer ships none. They are the
// application's own labels for its own editors, declared once in the
// application's own table and generated from there — which is the opposite of a
// library shipping a string and of an application keeping a second copy of a
// table. They are indexed by the LOCALE TABLE's order, which is persisted and
// append-only, so index 0 means nothing in particular.
export type SectionKey =
    | "home.about"
    | "home.footer"
    | "home.hero"
    | "home.inside"
    | "home.join"
    | "home.life"
    | "home.tafrah";

// The control a field asks for. What it looks like is the application's — a
// mapping is not a component.
export type SectionFieldType =
    | "Text"
    | "Url"
    | "Bool";

// One `const` per section, because a screen that edits one section ships one
// section — and a section is the only table here whose rows carry words, in
// every declared locale, which is the difference between a few hundred bytes
// and all of them.
export const sectionHomeAbout = {
    key: "home.about",
    sitePath: "/",
    fields: [
        {
            key: "heading",
            type: "Text",
            labels: ["Heading"],
            maxCodePoints: 160,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "kicker",
            type: "Text",
            labels: ["Kicker"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "p1",
            type: "Text",
            labels: ["First paragraph"],
            maxCodePoints: 1200,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "p2",
            type: "Text",
            labels: ["Second paragraph"],
            maxCodePoints: 1200,
            localized: false,
            required: false,
            choices: [],
        },
        {
            key: "tags",
            type: "Text",
            labels: ["Tags (comma separated)"],
            maxCodePoints: 300,
            localized: false,
            required: false,
            choices: [],
        },
    ],
    images: [],
} as const;

export const sectionHomeFooter = {
    key: "home.footer",
    sitePath: "/",
    fields: [
        {
            key: "address_line1",
            type: "Text",
            labels: ["Address, first line"],
            maxCodePoints: 120,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "address_line2",
            type: "Text",
            labels: ["Address, second line"],
            maxCodePoints: 120,
            localized: false,
            required: false,
            choices: [],
        },
        {
            key: "facebook",
            type: "Url",
            labels: ["Facebook link"],
            maxCodePoints: 256,
            localized: false,
            required: false,
            choices: [],
        },
        {
            key: "instagram",
            type: "Url",
            labels: ["Instagram link"],
            maxCodePoints: 256,
            localized: false,
            required: false,
            choices: [],
        },
        {
            key: "linkedin",
            type: "Url",
            labels: ["LinkedIn link"],
            maxCodePoints: 256,
            localized: false,
            required: false,
            choices: [],
        },
        {
            key: "note",
            type: "Text",
            labels: ["Footer note"],
            maxCodePoints: 240,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "tiktok",
            type: "Url",
            labels: ["TikTok link"],
            maxCodePoints: 256,
            localized: false,
            required: false,
            choices: [],
        },
    ],
    images: [],
} as const;

export const sectionHomeHero = {
    key: "home.hero",
    sitePath: "/",
    fields: [
        {
            key: "campus",
            type: "Text",
            labels: ["Campus"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "chapter",
            type: "Text",
            labels: ["Chapter"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "cta1",
            type: "Text",
            labels: ["Primary button"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "cta2",
            type: "Text",
            labels: ["Secondary button"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "headline1",
            type: "Text",
            labels: ["Headline, line 1"],
            maxCodePoints: 24,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "headline2",
            type: "Text",
            labels: ["Headline, line 2"],
            maxCodePoints: 24,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "headline3",
            type: "Text",
            labels: ["Headline, line 3"],
            maxCodePoints: 24,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "stat1_label",
            type: "Text",
            labels: ["Statistic 1 label"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "stat1_num",
            type: "Text",
            labels: ["Statistic 1 number"],
            maxCodePoints: 8,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "stat2_label",
            type: "Text",
            labels: ["Statistic 2 label"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "stat2_num",
            type: "Text",
            labels: ["Statistic 2 number"],
            maxCodePoints: 8,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "stat3_label",
            type: "Text",
            labels: ["Statistic 3 label"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "stat3_num",
            type: "Text",
            labels: ["Statistic 3 number"],
            maxCodePoints: 8,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "subtitle",
            type: "Text",
            labels: ["Subtitle"],
            maxCodePoints: 400,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "tagline",
            type: "Text",
            labels: ["Tagline"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
    ],
    images: [],
} as const;

export const sectionHomeInside = {
    key: "home.inside",
    sitePath: "/",
    fields: [
        {
            key: "desc",
            type: "Text",
            labels: ["Description"],
            maxCodePoints: 400,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "kicker",
            type: "Text",
            labels: ["Kicker"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "title",
            type: "Text",
            labels: ["Title"],
            maxCodePoints: 120,
            localized: false,
            required: true,
            choices: [],
        },
    ],
    images: [],
} as const;

export const sectionHomeJoin = {
    key: "home.join",
    sitePath: "/",
    fields: [
        {
            key: "closed_desc",
            type: "Text",
            labels: ["Closed banner text"],
            maxCodePoints: 400,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "closed_title",
            type: "Text",
            labels: ["Closed banner title"],
            maxCodePoints: 120,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "cta_closed",
            type: "Text",
            labels: ["Button while closed"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "cta_open",
            type: "Text",
            labels: ["Button while open"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "desc",
            type: "Text",
            labels: ["Description"],
            maxCodePoints: 600,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "kicker_closed",
            type: "Text",
            labels: ["Kicker while closed"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "kicker_open",
            type: "Text",
            labels: ["Kicker while open"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "note_closed",
            type: "Text",
            labels: ["Note while closed"],
            maxCodePoints: 200,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "note_open",
            type: "Text",
            labels: ["Note while open"],
            maxCodePoints: 200,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "open",
            type: "Bool",
            labels: ["Recruitment is open"],
            maxCodePoints: 0,
            localized: false,
            required: false,
            choices: [],
        },
        {
            key: "title",
            type: "Text",
            labels: ["Title"],
            maxCodePoints: 120,
            localized: false,
            required: true,
            choices: [],
        },
    ],
    images: [],
} as const;

export const sectionHomeLife = {
    key: "home.life",
    sitePath: "/",
    fields: [
        {
            key: "kicker",
            type: "Text",
            labels: ["Kicker"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "subtitle",
            type: "Text",
            labels: ["Subtitle"],
            maxCodePoints: 120,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "title",
            type: "Text",
            labels: ["Title"],
            maxCodePoints: 120,
            localized: false,
            required: true,
            choices: [],
        },
    ],
    images: [],
} as const;

export const sectionHomeTafrah = {
    key: "home.tafrah",
    sitePath: "/",
    fields: [
        {
            key: "desc",
            type: "Text",
            labels: ["Description"],
            maxCodePoints: 600,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "footer",
            type: "Text",
            labels: ["Footer line"],
            maxCodePoints: 300,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h1_desc",
            type: "Text",
            labels: ["Highlight 1 text"],
            maxCodePoints: 300,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h1_title",
            type: "Text",
            labels: ["Highlight 1 title"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h2_desc",
            type: "Text",
            labels: ["Highlight 2 text"],
            maxCodePoints: 300,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h2_title",
            type: "Text",
            labels: ["Highlight 2 title"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h3_desc",
            type: "Text",
            labels: ["Highlight 3 text"],
            maxCodePoints: 300,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h3_title",
            type: "Text",
            labels: ["Highlight 3 title"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h4_desc",
            type: "Text",
            labels: ["Highlight 4 text"],
            maxCodePoints: 300,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "h4_title",
            type: "Text",
            labels: ["Highlight 4 title"],
            maxCodePoints: 40,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "kicker",
            type: "Text",
            labels: ["Kicker"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "tagline",
            type: "Text",
            labels: ["Tagline"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "title",
            type: "Text",
            labels: ["Title"],
            maxCodePoints: 80,
            localized: false,
            required: true,
            choices: [],
        },
        {
            key: "visible",
            type: "Bool",
            labels: ["Show the Tafrah section"],
            maxCodePoints: 0,
            localized: false,
            required: false,
            choices: [],
        },
    ],
    images: [
        {
            slot: "site",
            labels: ["Platform screenshot"],
            minWidth: 320,
            minHeight: 200,
            aspect: null,
        },
    ],
} as const;

// The whole registry, for an editor that lists what there is to edit rather
// than knowing. A consumer that wants every section pays for every section,
// which is the choice being offered rather than made for them.
export const sections = {
    "home.about": sectionHomeAbout,
    "home.footer": sectionHomeFooter,
    "home.hero": sectionHomeHero,
    "home.inside": sectionHomeInside,
    "home.join": sectionHomeJoin,
    "home.life": sectionHomeLife,
    "home.tafrah": sectionHomeTafrah,
} as const;

// --- notification topics ----------------------------------------------------

// The same split the route table is under, applied to the other table that
// has one (`docs/01-seams.md` §4.1). A route's PATH is what calling it needs
// and a topic's KEY is what subscribing to it needs, so the key is the half
// withheld here — subscription is the disclosure, and a topic gated by a
// permission is one whose existence is part of what the permission protects.
//
// A bundle is a public file and a lazily loaded chunk is a public URL, so the
// key of a holder topic is in no bundle, no chunk and no source map. It
// arrives from the preferences endpoint, filtered by the server to the topics
// this holder may actually subscribe to, and a client re-attaches the entry it
// is given to the `const` below by CODE — which is why the code is emitted for
// every topic and the key is not.
//
// None of this is a boundary. anvil refuses the subscription, and for a topic
// that declares `stealthOnDenial` it refuses it the way it refuses a stealth
// route: as though the topic were not there.
export type TopicKey = never;

// Subscribable with no permission at all — the keys below are values.
export type PublicTopicKey = never;

// Everything else. The key is a type here and nowhere a value: this union is
// erased, and by the time a bundle exists there is nothing of it left.
export type HolderTopicKey = never;

export type TopicFanOut = never;

export type TopicScope = never;

// The transports anvil itself implements. A channel is not a row an
// application declares — adding one means shipping a sender — so this union is
// what the table holds and never more.
export type NotificationChannel = never;

// One `const` per topic. `userOptional` is false where the reader may not turn
// it off: a client that offers a switch there offers one the server refuses,
// and a security alert an account can silence is not an alert.
//
// `code` is a BIT POSITION in a stored preference mask and is append-only, the
// way a permission bit is. It is also the identity a holder topic is matched
// on, since its key is not here.

// The public tier as one table, for a client that resolves a key at run time.
// Only this tier can be a table at all — a holder topic has no key to put in
// one — which is the same sentence `publicRoutes` is under, for the same
// reason.
export const publicTopics = {} as const;

// --- analytics events -------------------------------------------------------

// What may be reported, and under what consent. One `const` per event and no
// table of them: a call site names the event it reports, so a screen that
// reports one ships one — and an aggregate would put every event's name into
// any bundle that touched a single one.
//
// `requiresConsent` is read at the door. An event that declares it is not
// queued pending a decision, because a buffer that flushes when consent
// arrives is a buffer of pre-consent data, which is the thing consent was
// about.
export type EventName =
    | "page_view";

export type EventClass =
    | "behaviour";

// A dimension's values are the CLOSED set the server stores an index into, so
// the `as const` is what makes a typo a compile error rather than a row the
// ingest path drops — and a dropped row is the analytics defect nobody notices
// for a quarter.
//
// An ENTITY dimension carries no values at all: it names a foreign id rather
// than a member of a set, and the server stores no index for it. It is emitted
// as `{ kind: "entity" }` rather than an empty array, so a consumer branching
// on shape sees the two cases rather than an enum with nothing in it — and the
// value it takes at a call site is a `Uuid`, encoded to the wire's 36-character
// form once, rather than a member of a union with no members.
export const eventPageView = {
    name: "page_view",
    code: 1,
    class: "behaviour",
    requiresConsent: false,
    dimensions: {},
} as const;

// --- accounts ---------------------------------------------------------------

// anvil's own account lifecycle — registration, verification, sign-in, a
// password reset and a credential change — described the way every other
// content table here is: `null` for an application that declares none, and a
// table of what it declared otherwise. There is no client here yet; this is
// the descriptor's shape and nothing that reads it.
//
// `routes` names only the roles the application actually has, in the fixed
// order above, and each value is the route's own generated `const` — never
// its id as a string — so a role naming a route anvil retires fails to
// compile rather than calling a path the server no longer answers.
export const kAccounts = {
    hashing: "client",
    activation: "immediate",
    contact: "email",
    identifiers: [
        { kind: "email", required: true, signIn: true },
    ],
    profile: [],
    secret: { minCodePoints: 12, maxCodePoints: 128, maxBytes: 1024 },
    codeDigits: 6,
    routes: {
        salt: routeAuthSalt,
        signIn: routeAuthLogin,
        change: routeAuthPassword,
        refresh: routeAuthRefresh,
        signOut: routeAuthLogout,
    },
} as const;

// A name for the shape above, so a consumer holding one before it is known
// whether the application declared accounts writes `AccountsTable | null`
// rather than spelling out `typeof kAccounts` at every boundary.
export type AccountsTable = typeof kAccounts;

// --- media ------------------------------------------------------------------

// A role is what an image is FOR, and it is the whole public grammar:
// `GET /media/{ns}/{id}/{role}`, built by the route builder and never by
// concatenation. The width is published BESIDE the role rather than instead of
// it, because a responsive `srcset` cannot exist without width descriptors —
// the browser has no basis on which to choose between the sources it is handed.
//
// Knowing a width was never the hazard. Building a URL out of one was, and
// there is no ladder here to build one from: no file extension, no format list,
// no rule from a width back to a path. A role→width mapping may change without
// a client release, and the addresses a client already holds keep working while
// it does.
//
// Bytes never enter the JS heap: this is an `<img src>` pointed at the media
// origin, not a fetch and a blob.
export type MediaNamespace =
    | "site";

export type MediaRole =
    | "thumb"
    | "card"
    | "hero"
    | "full";

// What a request with no role segment resolves to, and therefore what a caller
// that forgets the segment gets.
export const kMediaDefaultRole = "card";

// One table, because a namespace arrives with the object being rendered rather
// than being spelled at the call site.
export const kMediaWidths = {
    site: { thumb: 320, card: 640, hero: 1024, full: 1600 },
} as const;

// What each namespace will TAKE, which is the server's list and not a second
// one. It reaches two places and they have to agree: the `accept` attribute on
// a file input, which decides what the picker offers, and the check that runs
// against `File.type` before a byte is sent. An application that wrote this
// down itself kept a copy of something the server already enforces, and the
// copy is the one that goes stale — the symptom being an upload the picker
// offered and the server refused, or a file the picker hid and the server would
// have taken.
//
// Lowercase `type/subtype` with no parameters, which is the essence string a
// browser puts in `File.type`, so the comparison is `===` rather than a parse.
export const kMediaAccepts = {
    site: ["image/jpeg", "image/png"],
} as const;
