#pragma once

// Path construction and the one open primitive everything goes through
// (docs/07-filesystem.md §1, §3).
//
// Layout:
//     $STORAGE_ROOT/ns/<namespace>/<aa>/<bb>/<32 hex>            master
//     $STORAGE_ROOT/ns/<namespace>/<aa>/<bb>/<32 hex>.w640.avif  derived
//     $STORAGE_ROOT/tmp/<32 hex>.part                            in flight
//
// Every component is derived from a server-generated UUIDv4. Nothing here ever
// accepts a filename, an extension or a subdirectory from a request — that is
// the structural defence against traversal, because there is nothing to
// traverse with.
//
// Two levels of 256 give 65 536 buckets, and the sharding is not optional: one
// directory holding 10^6 entries makes every create and lookup slow on ext4
// even with dir_index, and makes readdir-based maintenance impractical.
//
// --- Why openat against a boot-time descriptor ---
//
// Resolving a path to a string and then opening it by name is a TOCTOU race: a
// process that can create a symlink inside STORAGE_ROOT between the check and
// the open wins it. Instead the namespace directories are opened ONCE at boot
// and every subsequent open is an openat walk relative to those descriptors,
// one component at a time, with O_NOFOLLOW on each. O_NOFOLLOW applies only to
// the final component of a path, so a single openat("aa/bb/<hex>") would leave
// the two shard components unprotected — hence the walk.

#include <sys/types.h>

#include <array>
#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <string_view>

#include "anvil/core/result.h"
#include "anvil/core/types.h"
#include "anvil/fs/namespace.h"
#include "anvil/fs/namespace_spec.h"

namespace anvil::fs {

// --- the modes EVERY writer under STORAGE_ROOT uses -------------------------
//
// Published here rather than kept as a literal in each writer, because the
// group bit is load-bearing and getting it wrong fails at the LAST step of a
// request the application has already authorised — so the symptom is a 404 or a
// 403 from Nginx on a path the handler just said yes to, with nothing in the
// application log at all.
//
// Nginx reads these files itself, once a handler has issued an
// X-Accel-Redirect, and it runs as its own user in the application's GROUP. So
// the owner and the group may read and nobody else may: 0750 on directories,
// 0640 on files. A deployment that runs Nginx outside that group must widen
// these, and is the one case where changing them is correct.
//
// It has now been got wrong twice by two independent writers — media uploads
// were 0600, which 403'd every image, and the CSV export was 0600, which meant
// no export ever downloaded. Two literals in two files is what let the
// second one happen after the first was fixed.
inline constexpr ::mode_t kStorageDirMode = 0750;
inline constexpr ::mode_t kStorageFileMode = 0640;

// --- variants --------------------------------------------------------------
//
// The width ladder, the role mapping and the format set live in
// anvil/fs/namespace.h and anvil/fs/namespace_spec.h rather than in
// anvil/images, because together they define the PATH GRAMMAR: a URL segment is
// accepted only if it names an entry, so the serving path must be able to
// validate one without linking libvips. The image pipeline derives its output
// set from the same constants.

// A width of 0 names the master, which has no suffix at all. Packing the two
// cases into one type keeps every path-building call site identical.
struct VariantKey final {
    std::uint16_t width;
    Format        format;

    [[nodiscard]] constexpr bool is_master() const noexcept { return width == 0; }
};

inline constexpr VariantKey kMasterVariant{0, Format::Avif};

[[nodiscard]] constexpr bool is_known_variant(VariantKey key) noexcept {
    if (key.is_master()) { return true; }
    for (const std::uint16_t width : kVariantWidths) {
        if (width == key.width) { return true; }
    }
    return false;
}

// --- relative paths --------------------------------------------------------

// "ns/" + namespace + "/aa/bb/" + 32 hex + ".w2560.avif" + NUL.
inline constexpr std::size_t kRelPathCapacity = 3 + kMaxNsDirLength + 7 + 32 + 11 + 1;

// A storage-relative path in automatic storage. No heap, no std::string, and
// NUL-terminated so it can be handed to openat without a copy.
class RelPath final {
public:
    [[nodiscard]] std::string_view view() const noexcept {
        return std::string_view{chars_.data(), size_};
    }
    [[nodiscard]] const char* c_str() const noexcept { return chars_.data(); }
    [[nodiscard]] std::size_t size() const noexcept { return size_; }

    // Only the builders below may produce one, so a RelPath in hand is always a
    // path this process constructed from server-generated bytes.
    friend RelPath media_relative_path(Ns ns, const Uuid& id, VariantKey key) noexcept;
    friend RelPath temp_relative_path(const Uuid& id) noexcept;
    friend RelPath derived_temp_path(const Uuid& id, VariantKey key) noexcept;
    friend RelPath shard_relative_path(Ns ns, const Uuid& id) noexcept;

private:
    RelPath() noexcept : chars_{}, size_{0} {}

    void append(std::string_view text) noexcept;
    void append_byte_hex(std::uint8_t byte) noexcept;
    void append_variant(VariantKey key) noexcept;

    std::array<char, kRelPathCapacity> chars_;
    std::uint8_t                       size_;
};

// An upper bound rather than an equality, because the capacity is derived from
// the LONGEST namespace directory name an application declares and that is
// legitimately its choice. The property being defended is unchanged — a relative
// path is built in automatic storage, fits one cache line, and never allocates —
// and an application whose namespace names outgrow the line fails the build here,
// which is the right place to find out.
static_assert(sizeof(RelPath) <= 64, "one cache line, zero heap");

// The path a media object occupies under STORAGE_ROOT. Total cost is a memcpy
// of a handful of bytes and 34 hex conversions — no allocation, no syscall.
[[nodiscard]] RelPath media_relative_path(Ns ns, const Uuid& id,
                                          VariantKey key = kMasterVariant) noexcept;

// "ns/<namespace>/<aa>/<bb>" — the directory the master and every variant share.
[[nodiscard]] RelPath shard_relative_path(Ns ns, const Uuid& id) noexcept;

// "tmp/<32 hex>.part" — the raw upload, as received.
[[nodiscard]] RelPath temp_relative_path(const Uuid& id) noexcept;

// "tmp/<32 hex>.m.tmp" for the normalised master, "tmp/<32 hex>.w640.avif.tmp"
// for a derived variant. Image work writes here and publishes by rename, so a
// libvips failure mid-encode can never leave a zero-byte file where a reader
// would find it (docs/08-images.md §5).
[[nodiscard]] RelPath derived_temp_path(const Uuid& id, VariantKey key) noexcept;

// "w640.avif" back into a VariantKey — the exact inverse of the suffix
// `media_relative_path` appends.
//
// It is NO LONGER part of the URL grammar: the public route takes a ROLE, and
// this spelling appears only as the name of a file on disk and as the `variant`
// field of the two staff responses. It stays because something has to be able to
// read that spelling back, and because a grammar with one writer and no reader
// is a grammar nothing checks. Rejects anything that is not exactly one table
// entry: no leading zeros, no unknown width, no unknown extension, no trailing
// bytes. Never throws, never allocates.
[[nodiscard]] std::optional<VariantKey> parse_variant(std::string_view text) noexcept;

// --- file descriptors ------------------------------------------------------

// One resource, RAII, rule of zero everywhere else. Every open in this
// subsystem produces one of these, so there is no raw close() in a normal path.
class Fd final {
public:
    Fd() noexcept : fd_{-1} {}
    explicit Fd(int fd) noexcept : fd_{fd} {}
    ~Fd() noexcept { reset(); }

    Fd(Fd&& other) noexcept : fd_{other.fd_} { other.fd_ = -1; }
    Fd& operator=(Fd&& other) noexcept {
        if (this != &other) {
            reset();
            fd_ = other.fd_;
            other.fd_ = -1;
        }
        return *this;
    }

    Fd(const Fd&) = delete;
    Fd& operator=(const Fd&) = delete;

    [[nodiscard]] int get() const noexcept { return fd_; }
    [[nodiscard]] bool valid() const noexcept { return fd_ >= 0; }
    [[nodiscard]] int release() noexcept {
        const int fd = fd_;
        fd_ = -1;
        return fd;
    }
    void reset() noexcept;

private:
    int fd_;
};

// --- the storage root ------------------------------------------------------

struct StorageStats final {
    std::uint64_t free_bytes;
    std::uint64_t total_bytes;
};

// Opened once at boot, before any pool starts, and read-only thereafter. The
// descriptors it holds are what makes every later open immune to a symlink
// planted under STORAGE_ROOT.
class Storage final {
public:
    // Verifies the root, creates tmp/ and the namespace directories, and asserts
    // that tmp/ and ns/ are on ONE filesystem — a cross-device rename degrades to
    // a copy and stops being atomic. Throws std::runtime_error on
    // any of those, because a storage layout this process cannot trust is a boot
    // failure, never a degraded mode.
    static void init(std::string_view storage_root);
    static void shutdown() noexcept;
    [[nodiscard]] static const Storage& instance();
    [[nodiscard]] static bool initialised() noexcept;

    // O_RDONLY|O_NOFOLLOW|O_CLOEXEC, walked component by component from the
    // namespace descriptor. An invalid Fd means "not there", which the caller
    // maps to a stealth 404 — it never distinguishes ENOENT from ELOOP to a
    // client, though the two are logged differently.
    [[nodiscard]] Fd open_media(Ns ns, const Uuid& id, VariantKey key) const noexcept;

    // Creates the two shard levels for `id` if they are absent and returns a
    // descriptor for the leaf. Called on the upload path only, never on a read.
    // The descriptor is what the publish rename targets and what is fsync'd
    // afterwards — resolving the directory by name a second time would reopen
    // the TOCTOU window the boot-time descriptors exist to close.
    [[nodiscard]] Result<Fd> open_shard_for_write(Ns ns, const Uuid& id) const noexcept;

    // Descriptors for the directories the upload path renames between. Borrowed,
    // never closed by the caller; valid for the life of the process.
    [[nodiscard]] int tmp_fd() const noexcept { return tmp_.get(); }
    [[nodiscard]] int ns_fd(Ns ns) const noexcept {
        return namespaces_[ns.index()].get();
    }
    [[nodiscard]] int root_fd() const noexcept { return root_.get(); }
    [[nodiscard]] std::string_view root() const noexcept { return root_path_; }

    // statvfs against the root. Used to refuse an upload before accepting bytes
    // rather than discovering a full disk halfway through one.
    [[nodiscard]] StorageStats stats() const noexcept;

    // Public only because make_unique needs it. init() is the sanctioned entry
    // point and the only caller in the process; a second instance would hold a
    // second set of descriptors to the same directories for no purpose.
    explicit Storage(std::string_view storage_root);

    Storage(const Storage&) = delete;
    Storage& operator=(const Storage&) = delete;

private:
    // Declaration order is construction order: root_ must be open before any
    // directory can be created relative to it.
    std::string                       root_path_;
    Fd                                root_;
    Fd                                tmp_;
    std::array<Fd, kNsCount>          namespaces_;
};

// --- the guard, exposed for the fuzz corpus --------------------------------
//
// Nothing on a request path calls this: request paths build a RelPath from a
// UUID and never see a string. It exists because §3 requires the canonicalise-
// and-compare rule to be written down once and testable, and because the
// sweeper validates paths it read back from disk.
//
// Returns the canonical absolute path when `candidate` — interpreted relative to
// STORAGE_ROOT — stays under STORAGE_ROOT after weakly_canonical, comparing
// whole PATH COMPONENTS. "/srv/storage-evil" has "/srv/storage" as a string
// prefix and is a different directory entirely. Absolute inputs,
// traversal, and anything that escapes return nullopt.
[[nodiscard]] std::optional<std::string> resolve_within_root(std::string_view root,
                                                             std::string_view candidate) noexcept;

}  // namespace anvil::fs
