#!/usr/bin/env bash
#
# The published surface is a committed file, and a change to it is a diff.
#
# hammer is a library, so every name reachable from an `exports` entry point is
# an API: a rename is a break in every application at once, and a break
# discovered by a consumer's build is the most expensive place to discover one.
# `ENGINEERING_RULES.md` §11.3 says a change to anything reachable from an entry point must
# be called out in the PR body with the migration an application has to perform,
# and `CHANGELOG.md` says the same thing to whoever is deciding whether to
# upgrade.
#
# Both of those are things a person remembers. This is the part that does not
# depend on remembering: the surface is in the repository, regenerating it is one
# command, and a change that was not intended shows up as a diff in review rather
# than as a support question.
#
# --- why types are in it as well as values ----------------------------------
#
# A type is erased at build and costs a consumer nothing at run time, which is
# exactly why removing one is easy to do by accident. It is still a compile error
# in every application that imported it. So the snapshot records both, and says
# which each name is.
#
# --- what it is NOT ---------------------------------------------------------
#
# It is not a signature check. A parameter added to an exported function does not
# move this file, and a semver decision still needs a person. What it catches is
# the class of change nobody meant to make: an export dropped by a refactor, one
# added by an over-eager barrel, a type that quietly became a value.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

committed="tools/public-surface.txt"

if [ ! -d node_modules/typescript ]; then
    printf 'FAIL  node_modules/typescript is missing. Run `npm ci`.\n' >&2
    exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

node - > "$work/surface.txt" <<'NODE_EOF'
import { readFileSync } from "node:fs";

import ts from "typescript";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));

// Read out of `exports` rather than listed, so an entry point added without a
// line here is impossible rather than merely discouraged.
const entries = [];
for (const [subpath, target] of Object.entries(pkg.exports ?? {})) {
    if (typeof target !== "string" || !target.startsWith("./dist/") || !target.endsWith(".js")) {
        continue;
    }
    entries.push({
        specifier: subpath === "." ? pkg.name : `${pkg.name}/${subpath.slice("./".length)}`,
        source: `src/${target.slice("./dist/".length, -".js".length)}.ts`,
    });
}
entries.sort((a, b) => (a.specifier < b.specifier ? -1 : 1));

const config = ts.readConfigFile("tsconfig.json", ts.sys.readFile);
const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, ".");
const program = ts.createProgram(
    entries.map((entry) => entry.source),
    { ...parsed.options, noEmit: true },
);
const checker = program.getTypeChecker();

const lines = [
    "# The published surface of every entry point in `exports`.",
    "#",
    "# Generated by tools/check-public-surface.sh, which diffs it. A change here",
    "# is an API change: it needs a CHANGELOG.md entry naming the migration, and",
    "# a semver decision (ENGINEERING_RULES.md §11.3).",
];

for (const entry of entries) {
    const file = program.getSourceFile(entry.source);
    if (file === undefined) {
        console.error(`FAIL  ${entry.source} is not in the program`);
        process.exit(1);
    }
    const module = checker.getSymbolAtLocation(file);
    lines.push("", `## ${entry.specifier}`);
    if (module === undefined) {
        lines.push("(no exports)");
        continue;
    }

    const named = [];
    for (const symbol of checker.getExportsOfModule(module)) {
        // Every export here is a re-export, so the symbol is an alias and its
        // flags describe the alias rather than the thing exported.
        const target =
            (symbol.flags & ts.SymbolFlags.Alias) !== 0 ? checker.getAliasedSymbol(symbol) : symbol;
        const isValue = (target.flags & ts.SymbolFlags.Value) !== 0;
        const isType = (target.flags & ts.SymbolFlags.Type) !== 0;
        const kind = isValue && isType ? "both " : isValue ? "value" : isType ? "type " : "other";
        named.push(`${kind} ${symbol.getName()}`);
    }
    named.sort();
    // Spelled rather than left blank: `hammer/codegen` is a command and exports
    // nothing, and an empty section reads like a generation that failed.
    lines.push(...(named.length === 0 ? ["(no exports)"] : named));
}

console.log(lines.join("\n"));
NODE_EOF

if [ ! -f "$committed" ]; then
    printf 'FAIL  %s is not committed. Write it:\n' "$committed" >&2
    printf '      tools/check-public-surface.sh --write\n' >&2
    exit 1
fi

if [ "${1:-}" = "--write" ]; then
    cp "$work/surface.txt" "$committed"
    printf 'public surface: written to %s\n' "$committed"
    exit 0
fi

if ! diff -u "$committed" "$work/surface.txt"; then
    printf '\nFAIL  the published surface moved. This is an API change (ENGINEERING_RULES.md §11.3):\n' >&2
    printf '      name the migration in CHANGELOG.md, decide the semver bump, then:\n' >&2
    printf '      tools/check-public-surface.sh --write\n' >&2
    exit 1
fi

printf 'public surface: clean\n'
