// Image processing.
//
// Fixtures are GENERATED by libvips rather than committed as binary files: a
// checked-in JPEG cannot be reviewed, and a test that depends on one drifts the
// moment someone re-exports it. The decompression-bomb case is the exception —
// it is a hand-built 51-byte PNG, because the whole point is a header that
// declares dimensions no real encoder would produce.

#include <array>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <string>
#include <vector>

#include <fcntl.h>
#include <unistd.h>

#include <gtest/gtest.h>

#include "namespaces.h"

#include "anvil/core/uuid.h"
#include "anvil/crypto/digest.h"
#include "anvil/fs/paths.h"
#include "anvil/fs/upload.h"
#include "anvil/images/crop.h"
#include "anvil/images/probe.h"
#include "anvil/images/strip.h"
#include "anvil/images/variants.h"

#if ANVIL_HAS_VIPS
#include <vips/vips.h>
#endif

namespace {

using anvil::Uuid;
namespace fs = anvil::fs;
namespace images = anvil::images;

class ImageFixture : public ::testing::Test {
protected:
    static void SetUpTestSuite() { images::init("anvil_tests"); }

    void SetUp() override {
        if (!images::available()) { GTEST_SKIP() << "built without libvips"; }
        std::array<char, 64> pattern{};
        std::snprintf(pattern.data(), pattern.size(), "/tmp/anvil-img-XXXXXX");
        const char* made = ::mkdtemp(pattern.data());
        ASSERT_NE(made, nullptr);
        root_ = made;
        fs::Storage::init(root_);
    }

    void TearDown() override {
        if (fs::Storage::initialised()) { fs::Storage::shutdown(); }
        std::error_code ec;
        std::filesystem::remove_all(root_, ec);
    }

#if ANVIL_HAS_VIPS
    // A real image of a given size, encoded into a file in the temp tree.
    [[nodiscard]] std::string make_image(std::string_view name, int width, int height,
                                         std::string_view suffix) {
        const std::string path = root_ + "/" + std::string{name} + std::string{suffix};
        VipsImage* base = nullptr;
        // A gradient rather than a flat colour: a flat image compresses to
        // almost nothing and would trip the compression-ratio guard.
        base = vips_image_new_matrixv(1, 1, 0.0);
        vips_object_unref_outputs(VIPS_OBJECT(base));
        g_object_unref(base);

        VipsImage* noise = nullptr;
        if (vips_gaussnoise(&noise, width, height, "mean", 128.0, "sigma", 60.0, nullptr) != 0) {
            return {};
        }
        VipsImage* cast = nullptr;
        if (vips_cast(noise, &cast, VIPS_FORMAT_UCHAR, nullptr) != 0) {
            g_object_unref(noise);
            return {};
        }
        g_object_unref(noise);

        VipsImage* rgb = nullptr;
        if (vips_bandjoin_const1(cast, &rgb, 0.0, nullptr) != 0) {
            g_object_unref(cast);
            return {};
        }
        g_object_unref(cast);

        const int written = vips_image_write_to_file(rgb, path.c_str(), nullptr);
        g_object_unref(rgb);
        return written == 0 ? path : std::string{};
    }

    [[nodiscard]] static fs::Fd open_read(const std::string& path) {
        return fs::Fd{::open(path.c_str(), O_RDONLY | O_CLOEXEC)};
    }

    [[nodiscard]] static std::uint64_t size_of(const std::string& path) {
        std::error_code ec;
        const auto size = std::filesystem::file_size(path, ec);
        return ec ? 0 : static_cast<std::uint64_t>(size);
    }
#endif

    std::string root_;
};

#if ANVIL_HAS_VIPS

// --- a decompression bomb dies on the header --------------------------------

TEST_F(ImageFixture, DeclaredGiantDimensionsAreRejectedOnTheHeader) {
    // A 51-byte PNG whose IHDR declares 50 000 x 50 000. At 4 bytes per pixel a
    // decoder would try to allocate 10 GB before any of our code ran.
    // Built by hand with a correct CRC so libvips parses the header and gets as
    // far as the dimensions, which is exactly where the rejection must happen.
    const std::string path = root_ + "/bomb.png";
    {
        std::array<std::uint8_t, 8> signature{
            {0x89, 'P', 'N', 'G', 0x0D, 0x0A, 0x1A, 0x0A}};
        // IHDR: length 13, type, 50000x50000, bit depth 8, colour type 6.
        std::array<std::uint8_t, 25> ihdr{{0x00, 0x00, 0x00, 0x0D, 'I', 'H', 'D', 'R',
                                           0x00, 0x00, 0xC3, 0x50, 0x00, 0x00, 0xC3, 0x50,
                                           0x08, 0x06, 0x00, 0x00, 0x00, 0, 0, 0, 0}};
        // CRC32 over type + data, computed here so the header is well-formed.
        std::uint32_t crc = 0xFFFFFFFFU;
        for (std::size_t i = 4; i < 21; ++i) {
            crc ^= ihdr[i];
            for (int bit = 0; bit < 8; ++bit) {
                crc = (crc >> 1U) ^ (0xEDB88320U & (~((crc & 1U) - 1U)));
            }
        }
        crc = ~crc;
        ihdr[21] = static_cast<std::uint8_t>(crc >> 24U);
        ihdr[22] = static_cast<std::uint8_t>(crc >> 16U);
        ihdr[23] = static_cast<std::uint8_t>(crc >> 8U);
        ihdr[24] = static_cast<std::uint8_t>(crc);

        std::FILE* file = std::fopen(path.c_str(), "wb");
        ASSERT_NE(file, nullptr);
        std::fwrite(signature.data(), 1, signature.size(), file);
        std::fwrite(ihdr.data(), 1, ihdr.size(), file);
        std::fclose(file);
    }

    const fs::Fd fd = open_read(path);
    ASSERT_TRUE(fd.valid());
    const anvil::Result<images::ImageInfo> probed = images::probe(fd.get(), size_of(path));
    ASSERT_FALSE(probed.ok());
    // Either the dimension cap or the pixel cap fires first; both are rejections
    // on the header, and neither decodes anything.
    EXPECT_TRUE(probed.error().field == images::kRejectDimension ||
                probed.error().field == images::kRejectPixels ||
                probed.error().field == images::kRejectRatio ||
                probed.error().field == images::kRejectUnreadable);
}

// --- over the byte cap, rejected before decode ------------------------------

TEST_F(ImageFixture, OversizedFileIsRejectedBeforeDecode) {
    const std::string path = make_image("small", 64, 64, ".png");
    ASSERT_FALSE(path.empty());

    const fs::Fd fd = open_read(path);
    ASSERT_TRUE(fd.valid());

    // The declared size is what the caller measured; one byte over the cap must
    // fail without the decoder being handed anything.
    const anvil::Result<images::ImageInfo> probed =
        images::probe(fd.get(), images::kMaxBytes + 1);
    ASSERT_FALSE(probed.ok());
    EXPECT_EQ(probed.error().code, anvil::ErrorCode::PayloadTooLarge);
    EXPECT_EQ(probed.error().field, images::kRejectBytes);
}

// --- multi-frame images are rejected ----------------------------------------

TEST_F(ImageFixture, AnimatedImagesAreRejectedOnTheFrameCount) {
    // A hand-built two-frame GIF89a, byte for byte. libvips' savers on this
    // machine will not emit a multi-page file from a page-height strip, and a
    // test that silently skipped would leave the one guard standing between
    // this service and a 1000-frame upload untested (docs/08-images.md §1 step 4).
    //
    // A frame count multiplies EVERY cost, and each frame here passes a
    // per-frame dimension check trivially — which is the whole point.
    const std::array<std::uint8_t, 8> header{{'G', 'I', 'F', '8', '9', 'a',
                                              0x01, 0x00}};             // 1 px wide
    const std::array<std::uint8_t, 5> screen{{0x01, 0x00,               // 1 px high
                                              0x80,                     // global table, 2 colours
                                              0x00, 0x00}};
    const std::array<std::uint8_t, 6> palette{{0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00}};
    // Graphic control extension, image descriptor, then one LZW sub-block:
    // clear (4), pixel index 0, end-of-information (5), packed LSB-first.
    const std::array<std::uint8_t, 23> frame{{0x21, 0xF9, 0x04, 0x00, 0x0A, 0x00, 0x00, 0x00,
                                              0x2C, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01,
                                              0x00, 0x00, 0x02, 0x02, 0x44, 0x01, 0x00}};

    const std::string path = root_ + "/animated.gif";
    {
        std::FILE* file = std::fopen(path.c_str(), "wb");
        ASSERT_NE(file, nullptr);
        std::fwrite(header.data(), 1, header.size(), file);
        std::fwrite(screen.data(), 1, screen.size(), file);
        std::fwrite(palette.data(), 1, palette.size(), file);
        std::fwrite(frame.data(), 1, frame.size(), file);
        std::fwrite(frame.data(), 1, frame.size(), file);
        const std::uint8_t trailer = 0x3B;
        std::fwrite(&trailer, 1, 1, file);
        std::fclose(file);
    }

    // The fixture must really be multi-page, or this test proves nothing.
    VipsImage* check = vips_image_new_from_file(path.c_str(), nullptr);
    ASSERT_NE(check, nullptr) << vips_error_buffer();
    const int pages = vips_image_get_n_pages(check);
    g_object_unref(check);
    ASSERT_EQ(pages, 2) << "the hand-built GIF is not being read as two frames";

    const fs::Fd fd = open_read(path);
    ASSERT_TRUE(fd.valid());
    const anvil::Result<images::ImageInfo> probed = images::probe(fd.get(), size_of(path));
    ASSERT_FALSE(probed.ok()) << "a two-frame animation was accepted";
    EXPECT_EQ(probed.error().field, images::kRejectFrames);
}

// --- the compression ratio guard --------------------------------------------

TEST_F(ImageFixture, AnAbsurdCompressionRatioIsRejected) {
    // A flat 4000x4000 image is a few kilobytes of PNG and 48 MB of pixels.
    // That is what a bomb looks like from the outside, and no photograph
    // compresses anywhere near that well (docs/08-images.md §1 step 5).
    const std::string path = root_ + "/flat.png";
    VipsImage* flat = nullptr;
    ASSERT_EQ(vips_black(&flat, 4000, 4000, "bands", 3, nullptr), 0);
    const int saved = vips_image_write_to_file(flat, path.c_str(), nullptr);
    g_object_unref(flat);
    ASSERT_EQ(saved, 0);

    const fs::Fd fd = open_read(path);
    ASSERT_TRUE(fd.valid());
    const std::uint64_t bytes = size_of(path);
    ASSERT_GT(bytes, 0U);
    // Sanity: the fixture really is a pathological ratio, not merely a big file.
    ASSERT_GT((4000ULL * 4000ULL * 3ULL) / bytes, images::kMaxCompressionRatio);

    const anvil::Result<images::ImageInfo> probed = images::probe(fd.get(), bytes);
    ASSERT_FALSE(probed.ok());
    EXPECT_EQ(probed.error().field, images::kRejectRatio);
}

// --- a wide-gamut profile becomes sRGB --------------------------------------

TEST_F(ImageFixture, AWideGamutProfileIsConvertedToSrgbAndDropped) {
    const std::string path = make_image("p3", 200, 150, ".png");
    ASSERT_FALSE(path.empty());

    // Tag the file with a Display P3 profile, which is what a modern phone
    // produces. Stripping it without converting is what renders these images
    // desaturated.
    VipsImage* loaded = vips_image_new_from_file(path.c_str(), nullptr);
    ASSERT_NE(loaded, nullptr);
    VipsImage* tagged = nullptr;
    if (vips_icc_export(loaded, &tagged, "output_profile", "p3", nullptr) != 0) {
        vips_error_clear();
        g_object_unref(loaded);
        GTEST_SKIP() << "this build has no lcms colour management";
    }
    ASSERT_EQ(vips_image_write_to_file(tagged, path.c_str(), nullptr), 0);
    ASSERT_NE(vips_image_get_typeof(tagged, VIPS_META_ICC_NAME), 0u)
        << "the fixture did not actually carry a profile";
    g_object_unref(tagged);
    g_object_unref(loaded);

    const fs::Fd source = open_read(path);
    ASSERT_TRUE(source.valid());
    const std::string out_path = root_ + "/p3.out.png";
    const fs::Fd out{::open(out_path.c_str(), O_RDWR | O_CREAT | O_TRUNC | O_CLOEXEC, 0600)};
    ASSERT_TRUE(out.valid());

    const anvil::Result<images::ImageInfo> normalised =
        images::normalise_master(source.get(), fs::Mime::Png, out.get());
    ASSERT_TRUE(normalised.ok());

    VipsImage* result = vips_image_new_from_file(out_path.c_str(), nullptr);
    ASSERT_NE(result, nullptr);
    // Converted, then dropped: the output is unambiguous sRGB and carries no
    // profile, so every variant derived from it is consistent.
    EXPECT_EQ(vips_image_get_typeof(result, VIPS_META_ICC_NAME), 0u)
        << "the ICC profile survived into the master";
    EXPECT_EQ(vips_image_get_interpretation(result), VIPS_INTERPRETATION_sRGB);

    // The pixels are still a picture: a failed transform that produced black or
    // white would satisfy every assertion above.
    double mean = 0.0;
    ASSERT_EQ(vips_avg(result, &mean, nullptr), 0);
    EXPECT_GT(mean, 5.0);
    EXPECT_LT(mean, 250.0);
    g_object_unref(result);
}

// --- no CPU oversubscription ------------------------------------------------

TEST_F(ImageFixture, LibvipsRunsSingleThreadedPerTask) {
    // libvips parallelises internally by default. N cpu_pool threads each
    // spawning M workers oversubscribes the CPU badly, and the pool size is
    // already the concurrency decision.
    EXPECT_EQ(vips_concurrency_get(), 1);
    // The operation cache holds DECODED images; left at its default it grows
    // straight into the per-task RSS budget.
    EXPECT_EQ(vips_cache_get_max(), 0);
    EXPECT_EQ(vips_cache_get_max_mem(), 0U);
}

TEST_F(ImageFixture, LegitimatePhotoPassesTheProbe) {
    const std::string path = make_image("photo", 800, 600, ".png");
    ASSERT_FALSE(path.empty());

    const fs::Fd fd = open_read(path);
    ASSERT_TRUE(fd.valid());
    const anvil::Result<images::ImageInfo> probed = images::probe(fd.get(), size_of(path));
    ASSERT_TRUE(probed.ok()) << static_cast<int>(probed.error().code);
    EXPECT_EQ(probed.value().width, 800U);
    EXPECT_EQ(probed.value().height, 600U);
    EXPECT_EQ(probed.value().pages, 1U);
}

// --- orientation applied, metadata gone -------------------------------------

TEST_F(ImageFixture, EveryExifOrientationRendersUprightAndTheTagIsRemoved) {
    // A 40x20 landscape image. Orientations 5-8 transpose, so an image that was
    // tagged with one of them must come out 20x40 — that is the difference
    // between "applied to the pixels" and "tag silently dropped".
    for (int orientation = 1; orientation <= 8; ++orientation) {
        const std::string name = "orient" + std::to_string(orientation);
        const std::string path = make_image(name, 40, 20, ".jpg");
        ASSERT_FALSE(path.empty());

        // Tag it and rewrite.
        VipsImage* loaded = vips_image_new_from_file(path.c_str(), nullptr);
        ASSERT_NE(loaded, nullptr);
        vips_image_set_int(loaded, VIPS_META_ORIENTATION, orientation);
        ASSERT_EQ(vips_image_write_to_file(loaded, path.c_str(), nullptr), 0);
        g_object_unref(loaded);

        const fs::Fd source = open_read(path);
        ASSERT_TRUE(source.valid());
        const std::string out_path = root_ + "/" + name + ".out.jpg";
        const fs::Fd out{::open(out_path.c_str(), O_RDWR | O_CREAT | O_TRUNC | O_CLOEXEC, 0600)};
        ASSERT_TRUE(out.valid());

        const anvil::Result<images::ImageInfo> normalised =
            images::normalise_master(source.get(), fs::Mime::Jpeg, out.get());
        ASSERT_TRUE(normalised.ok()) << "orientation " << orientation;

        const bool transposed = orientation >= 5;
        EXPECT_EQ(normalised.value().width, transposed ? 20U : 40U)
            << "orientation " << orientation << " was not applied to the pixels";
        EXPECT_EQ(normalised.value().height, transposed ? 40U : 20U);

        // The tag itself is gone, so no downstream consumer rotates a second
        // time.
        VipsImage* result = vips_image_new_from_file(out_path.c_str(), nullptr);
        ASSERT_NE(result, nullptr);
        EXPECT_EQ(vips_image_get_typeof(result, VIPS_META_ORIENTATION), 0)
            << "orientation tag survived for value " << orientation;
        // And so is everything else: EXIF, XMP, IPTC, the embedded thumbnail.
        EXPECT_EQ(vips_image_get_typeof(result, VIPS_META_EXIF_NAME), 0);
        EXPECT_EQ(vips_image_get_typeof(result, VIPS_META_XMP_NAME), 0);
        EXPECT_EQ(vips_image_get_typeof(result, VIPS_META_IPTC_NAME), 0);
        EXPECT_EQ(vips_image_get_typeof(result, "exif-ifd0-Make"), 0);
        EXPECT_EQ(vips_image_get_typeof(result, "exif-ifd3-GPSLatitude"), 0);
        g_object_unref(result);
    }
}

// --- no upscaling -----------------------------------------------------------

TEST_F(ImageFixture, AMasterNarrowerThanAVariantProducesNoSuchVariant) {
    const std::string path = make_image("narrow", 800, 500, ".png");
    ASSERT_FALSE(path.empty());
    const fs::Fd master = open_read(path);
    ASSERT_TRUE(master.valid());

    const Uuid id = anvil::uuid::generate_v4();
    const anvil::Result<std::vector<images::VariantRecord>> variants =
        images::generate_variants(fs::Storage::instance(), testapp::kContent, id, master.get(),
                                  images::ImageInfo{800, 500, 1});
    ASSERT_TRUE(variants.ok()) << static_cast<int>(variants.error().code);

    for (const images::VariantRecord& variant : variants.value()) {
        EXPECT_LE(variant.width, 800U) << "a variant was upscaled past the master";
        EXPECT_GT(variant.bytes, 0U) << "a zero-byte variant was recorded";
    }
    // 320 and 640 only, in every format this build can encode.
    const std::size_t formats = images::can_encode_avif() ? 2U : 1U;
    EXPECT_EQ(variants.value().size(), 2U * formats);
}

// --- variants come from the master, never zero-byte -------------------------

TEST_F(ImageFixture, EveryRecordedVariantExistsOnDiskWithTheRecordedSize) {
    const std::string path = make_image("full", 1200, 900, ".png");
    ASSERT_FALSE(path.empty());
    const fs::Fd master = open_read(path);
    ASSERT_TRUE(master.valid());

    const Uuid id = anvil::uuid::generate_v4();
    const anvil::Result<std::vector<images::VariantRecord>> variants =
        images::generate_variants(fs::Storage::instance(), testapp::kMedia, id, master.get(),
                                  images::ImageInfo{1200, 900, 1});
    ASSERT_TRUE(variants.ok());
    ASSERT_FALSE(variants.value().empty());

    for (const images::VariantRecord& variant : variants.value()) {
        const fs::VariantKey key{variant.width, variant.format};
        const std::filesystem::path on_disk =
            std::filesystem::path{root_} /
            std::string{fs::media_relative_path(testapp::kMedia, id, key).view()};
        ASSERT_TRUE(std::filesystem::exists(on_disk)) << on_disk;
        EXPECT_EQ(std::filesystem::file_size(on_disk), variant.bytes);
        // Aspect ratio preserved: height follows the width.
        EXPECT_NEAR(static_cast<double>(variant.width) / variant.height, 1200.0 / 900.0, 0.02);
    }

    // No temp file survives a successful run.
    for (const images::VariantRecord& variant : variants.value()) {
        const fs::VariantKey key{variant.width, variant.format};
        const std::filesystem::path temp =
            std::filesystem::path{root_} / std::string{fs::derived_temp_path(id, key).view()};
        EXPECT_FALSE(std::filesystem::exists(temp));
    }
}

// --- crop is non-destructive ------------------------------------------------

TEST_F(ImageFixture, CropLeavesTheMasterByteIdentical) {
    const std::string path = make_image("croppable", 1200, 900, ".png");
    ASSERT_FALSE(path.empty());

    // The master, as stored.
    const Uuid id = anvil::uuid::generate_v4();
    {
        const anvil::Result<fs::Fd> shard =
            fs::Storage::instance().open_shard_for_write(testapp::kGuest, id);
        ASSERT_TRUE(shard.ok());
        const std::filesystem::path master_path =
            std::filesystem::path{root_} /
            std::string{fs::media_relative_path(testapp::kGuest, id).view()};
        std::error_code ec;
        std::filesystem::copy_file(path, master_path, ec);
        ASSERT_FALSE(ec) << ec.message();
    }

    const std::filesystem::path master_path =
        std::filesystem::path{root_} /
        std::string{fs::media_relative_path(testapp::kGuest, id).view()};
    const std::uint64_t before_size = size_of(master_path.string());
    const anvil::crypto::Digest256 before = [&master_path] {
        std::FILE* file = std::fopen(master_path.c_str(), "rb");
        std::vector<std::uint8_t> bytes;
        std::array<std::uint8_t, 4096> buffer{};
        std::size_t read = 0;
        while ((read = std::fread(buffer.data(), 1, buffer.size(), file)) > 0) {
            bytes.insert(bytes.end(), buffer.begin(), buffer.begin() + read);
        }
        std::fclose(file);
        return anvil::crypto::sha256(bytes);
    }();

    const images::ImageInfo info{1200, 900, 1};

    // Crop, change it, remove it. The master is opened READ-ONLY throughout.
    for (const images::CropRect rect : {images::CropRect{0.1F, 0.1F, 0.8F, 0.8F},
                                        images::CropRect{0.0F, 0.0F, 0.5F, 0.5F},
                                        images::CropRect{0.0F, 0.0F, 1.0F, 1.0F}}) {
        const fs::Fd master = open_read(master_path.string());
        ASSERT_TRUE(master.valid());
        const anvil::Result<std::vector<images::VariantRecord>> derived = images::apply_crop(
            fs::Storage::instance(), testapp::kGuest, id, master.get(), info, rect);
        ASSERT_TRUE(derived.ok()) << static_cast<int>(derived.error().code);
    }

    EXPECT_EQ(size_of(master_path.string()), before_size);
    const anvil::crypto::Digest256 after = [&master_path] {
        std::FILE* file = std::fopen(master_path.c_str(), "rb");
        std::vector<std::uint8_t> bytes;
        std::array<std::uint8_t, 4096> buffer{};
        std::size_t read = 0;
        while ((read = std::fread(buffer.data(), 1, buffer.size(), file)) > 0) {
            bytes.insert(bytes.end(), buffer.begin(), buffer.begin() + read);
        }
        std::fclose(file);
        return anvil::crypto::sha256(bytes);
    }();
    EXPECT_EQ(before, after) << "the master was modified by a crop";
}

// --- malformed input under ASan ---------------------------------------------

TEST_F(ImageFixture, MalformedInputIsRejectedRatherThanCrashing) {
    // Truncations and corruptions of real files: the decoders are memory-unsafe
    // C libraries and this whole suite runs under ASan (docs/08-images.md §1).
    const std::string source = make_image("fuzzseed", 128, 96, ".png");
    ASSERT_FALSE(source.empty());

    std::vector<std::uint8_t> bytes;
    {
        std::FILE* file = std::fopen(source.c_str(), "rb");
        ASSERT_NE(file, nullptr);
        std::array<std::uint8_t, 4096> buffer{};
        std::size_t read = 0;
        while ((read = std::fread(buffer.data(), 1, buffer.size(), file)) > 0) {
            bytes.insert(bytes.end(), buffer.begin(), buffer.begin() + read);
        }
        std::fclose(file);
    }
    ASSERT_GT(bytes.size(), 64U);

    for (std::size_t cut = 8; cut < bytes.size(); cut = cut * 2 + 1) {
        std::vector<std::uint8_t> mutated{bytes.begin(), bytes.begin() + cut};
        // Flip a byte in the middle as well, so the corpus is not only
        // truncations.
        if (mutated.size() > 20) { mutated[mutated.size() / 2] ^= 0xFFU; }

        const std::string path = root_ + "/fuzz" + std::to_string(cut) + ".png";
        std::FILE* file = std::fopen(path.c_str(), "wb");
        ASSERT_NE(file, nullptr);
        std::fwrite(mutated.data(), 1, mutated.size(), file);
        std::fclose(file);

        const fs::Fd fd = open_read(path);
        ASSERT_TRUE(fd.valid());
        // The contract is "returns", not "succeeds": a rejection is the expected
        // outcome and a crash is the failure this case exists to catch.
        const anvil::Result<images::ImageInfo> probed =
            images::probe(fd.get(), mutated.size());
        if (probed.ok()) {
            const std::string out_path = root_ + "/fuzz" + std::to_string(cut) + ".out.png";
            const fs::Fd out{
                ::open(out_path.c_str(), O_RDWR | O_CREAT | O_TRUNC | O_CLOEXEC, 0600)};
            ASSERT_TRUE(out.valid());
            (void)images::normalise_master(fd.get(), fs::Mime::Png, out.get());
        }
    }
}

// --- crop validation --------------------------------------------------------

TEST(ImageCrop, RectangleIsValidatedAgainstBoundsAndTheSmallestVariant) {
    const images::ImageInfo master{1200, 900, 1};

    EXPECT_TRUE(images::validate_crop(images::CropRect{0.0F, 0.0F, 1.0F, 1.0F}, master).ok());
    EXPECT_TRUE(images::validate_crop(images::CropRect{0.25F, 0.25F, 0.5F, 0.5F}, master).ok());

    // Outside the image.
    EXPECT_FALSE(images::validate_crop(images::CropRect{0.5F, 0.0F, 0.6F, 0.5F}, master).ok());
    EXPECT_FALSE(images::validate_crop(images::CropRect{-0.1F, 0.0F, 0.5F, 0.5F}, master).ok());
    // Empty.
    EXPECT_FALSE(images::validate_crop(images::CropRect{0.0F, 0.0F, 0.0F, 0.5F}, master).ok());
    // NaN and infinity fail every comparison, so they are excluded explicitly.
    const float nan = std::numeric_limits<float>::quiet_NaN();
    EXPECT_FALSE(images::validate_crop(images::CropRect{nan, 0.0F, 0.5F, 0.5F}, master).ok());
    EXPECT_FALSE(images::validate_crop(
                     images::CropRect{0.0F, 0.0F, std::numeric_limits<float>::infinity(), 0.5F},
                     master)
                     .ok());
    // Narrower than the smallest target width: every variant would be an
    // upscale, which looks worse than not cropping.
    EXPECT_FALSE(images::validate_crop(images::CropRect{0.0F, 0.0F, 0.2F, 0.2F}, master).ok());
}

#endif  // ANVIL_HAS_VIPS

}  // namespace
