// DO NOT EDIT. Generated by hammer codegen.
//
// Regenerate with:
//
//     hammer codegen --descriptor <descriptor.json> --out <dir>
//
// Descriptor format: 3
// Tables: sha256 e8789d7d0d9ebc04006532f3c147a7410b2e5330932c283b68cfaed47bbee17e
//
// Nothing above `tables` in the descriptor reaches this file, and the
// omission is the reason the hash covers `tables` and nothing else: an
// application's version changes on every release and changes no table, so a
// module carrying it would diff on every release and be regenerated for
// nothing. The hash answers the one question worth failing a build over —
// whether this client was generated from these tables.
//
// The module has no side effects and no default export, and every table is
// an individual `const`. A bundler can drop an export nothing references; it
// cannot drop one member of an object something imported.

// --- the client's provenance ------------------------------------------------

export const kDescriptorFormat = 3;

// Compared against the hash the session response carries. A mismatch is a
// stale bundle, and it is surfaced rather than acted on: an automatic reload
// discards whatever the user had typed, on the deploy most likely to be
// happening during working hours (docs/00-architecture.md §7.1).
export const kTablesHash = "e8789d7d0d9ebc04006532f3c147a7410b2e5330932c283b68cfaed47bbee17e";

// --- error codes ------------------------------------------------------------

// The wire names, unchanged. A second spelling would be a translation table
// in every bundle that decodes an envelope, a second copy of an enum that is
// append-only server-side, and a word on a screen that does not match the
// word in the log somebody is reading it against.
//
// `Unknown` is hammer's, and its shape is deliberate: anvil's enumerators are
// SCREAMING_SNAKE, so no code it appends can collide with it. A client that
// threw on a code added this morning would turn a deploy into an outage in
// every tab that was already open.
export type ErrorCode =
    | "UNAUTHENTICATED"
    | "FORBIDDEN"
    | "NOT_FOUND"
    | "CAPABILITY_REQUIRED"
    | "CAPABILITY_INVALID"
    | "VALIDATION_FAILED"
    | "CONFLICT"
    | "VERSION_MISMATCH"
    | "RATE_LIMITED"
    | "PAYLOAD_TOO_LARGE"
    | "UNSUPPORTED_MEDIA"
    | "SERVICE_UNAVAILABLE"
    | "INTERNAL"
    | "INSUFFICIENT_STORAGE"
    | "Unknown";

// The member that is not a failure, and therefore not a member of the union
// above: an application would otherwise owe a sentence for a case no error
// surface can reach.
export const kErrorCodeOk = "OK";

// Every member with the value anvil stores, the success member included. The
// decode needs the set of names; the numbers are here because anvil keeps them
// in audit rows that are read back long after the deploy that wrote them.
export const kErrorCodeValues = {
    OK: 0,
    UNAUTHENTICATED: 1,
    FORBIDDEN: 2,
    NOT_FOUND: 3,
    CAPABILITY_REQUIRED: 4,
    CAPABILITY_INVALID: 5,
    VALIDATION_FAILED: 6,
    CONFLICT: 7,
    VERSION_MISMATCH: 8,
    RATE_LIMITED: 9,
    PAYLOAD_TOO_LARGE: 10,
    UNSUPPORTED_MEDIA: 11,
    SERVICE_UNAVAILABLE: 12,
    INTERNAL: 13,
    INSUFFICIENT_STORAGE: 14,
} as const;

// The bound the decode can state, because the enum is append-only.
export const kErrorCodeMaxValue = 14;

// Carried for the contract suite rather than for the run time: hammer branches
// on the code, and this is what asserts the server still maps it the way it did.
export const kErrorCodeHttpStatus = {
    OK: 200,
    UNAUTHENTICATED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CAPABILITY_REQUIRED: 428,
    CAPABILITY_INVALID: 403,
    VALIDATION_FAILED: 400,
    CONFLICT: 409,
    VERSION_MISMATCH: 409,
    RATE_LIMITED: 429,
    PAYLOAD_TOO_LARGE: 413,
    UNSUPPORTED_MEDIA: 415,
    SERVICE_UNAVAILABLE: 503,
    INTERNAL: 500,
    INSUFFICIENT_STORAGE: 507,
} as const;

// The codes the stealth filter rewrites to a 404. A client needs them to know
// that a not-found answer on a stealth route is not evidence of anything — and
// that rendering a denial there rebuilds the oracle the server removed.
export const kStealthHiddenErrorCodes = [
    "UNAUTHENTICATED",
    "FORBIDDEN",
    "CAPABILITY_REQUIRED",
    "CAPABILITY_INVALID",
] as const;

// --- validation reasons -----------------------------------------------------

// anvil names the reason a field failed and never the sentence. The map from a
// reason to words is `Record<ValidationReason, string>` in the application, so a
// reason added server-side is a compile error in every client until somebody
// writes them — the alternative is a fallback string, and a fallback string is
// how a wire enumerator reaches a user in an interface that is otherwise
// entirely in Arabic.
//
// `Unknown` is here for the reason it is in `ErrorCode`, and it is the
// member that makes the compile error above safe to rely on. `Reason` is
// append-only server-side too, so a deploy can answer an open tab with a
// reason its bundle predates. The alternative to a member is dropping the
// field from the map, which is a form that refuses to submit with nothing
// marked on it — and that is worse than a sentence that is too general.
export type ValidationReason =
    | "REQUIRED"
    | "TOO_SHORT"
    | "TOO_LONG"
    | "BAD_FORMAT"
    | "BAD_CHARSET"
    | "OUT_OF_RANGE"
    | "NOT_ALLOWED"
    | "BAD_CHECKSUM"
    | "WEAK"
    | "BREACHED"
    | "Unknown";

export const kValidationReasonValues = {
    OK: 0,
    REQUIRED: 1,
    TOO_SHORT: 2,
    TOO_LONG: 3,
    BAD_FORMAT: 4,
    BAD_CHARSET: 5,
    OUT_OF_RANGE: 6,
    NOT_ALLOWED: 7,
    BAD_CHECKSUM: 8,
    WEAK: 9,
    BREACHED: 10,
} as const;

// --- permissions ------------------------------------------------------------

// One `const` per bit and no table of names. A membership test is
// `permissions.has(kPermContentRead)` — a number against sixteen bytes — and the
// union below is erased, so a bundle carries no permission name at all.
//
// An application that has to SHOW a permission's name writes it as
// `Record<Permission, string>`, which is copy, and copy is the application's
// (docs/01-seams.md §13). It is then total by type: a permission added
// server-side is a compile error until it has a word.
//
// Bit indices are stored in access tokens and in the user document and are
// never renumbered. A renumber is a silent regrant of authority, and it is not
// something this side can check.
export type Permission =
    | "SuperAdmin"
    | "HrManager"
    | "ContentEditor";

export const kPermSuperAdmin = 0;
export const kPermHrManager = 1;
export const kPermContentEditor = 2;

// The one place a table of names is unavoidable, and it is its own `const` for
// exactly that reason.
//
// anvil sends a holder's permissions on the session response as NAMES in bit
// order rather than as a mask — `for_each_name` skips the reserved gaps between
// an application's blocks, so a bit nothing names never reaches a client as a
// control that authorises nothing — and nothing can turn a name back into a bit
// without the map. `SessionStore` takes it, and a chunk that decodes no session
// references it and therefore ships none of these names.
//
// That is the whole reason it is not a member of `kApiTables`: putting it there
// would put every permission name into any bundle that constructs a client,
// including the one an anonymous visitor downloads.
export const kPermissionBits = {
    SuperAdmin: kPermSuperAdmin,
    HrManager: kPermHrManager,
    ContentEditor: kPermContentEditor,
} as const;

// --- locales ----------------------------------------------------------------

// In the server's order, which is persisted and append-only: anvil stores a
// locale as a one-byte index into this table. Never sorted, never renumbered,
// and index 0 means nothing in particular.
//
// `collation` is carried so a client-side sort agrees with the server's. They
// are otherwise two different orderings of the same rows, and the disagreement
// shows up exactly at a page boundary — where a row appears twice, or never.
export type Locale =
    | "en";

export const kLocales = [
    { tag: "en", collation: "en", rtl: false },
] as const;

// --- capability scopes ------------------------------------------------------

// A route declaring a scope takes a `Capability<Scope>` in its parameters, and
// the only producer of one is the call that mints it — so the requirement is
// discharged by the compiler rather than by a reviewer.
//
// No TTL here. A scope declares whether redemption burns the token; how long a
// particular token lives is a property of that token, set where it is minted.
export type CapabilityScope = never;

export const kCapabilityScopeValues = {} as const;

// Whether redemption burns the token. A call carrying a single-use capability
// is never auto-retried: the server consumed it whether or not the response
// arrived, so a retry gets CAPABILITY_INVALID and reports a failure for an
// operation that succeeded. The recovery is a re-read, not a retry.
export const kCapabilitySingleUse = {} as const;

// --- rate limits ------------------------------------------------------------

// Advisory, and not the limit — the server's is. The client's copy exists so an
// interface does not spend a user's budget on its own retries and then present
// them with a lockout they did not cause.
//
// A 429 holds back the whole bucket rather than the one call. Retrying the
// other nine while one waits is how a rate limit becomes a lockout.
export type RateLimitBucket = never;

export const kRateLimits = {} as const;

// --- limits -----------------------------------------------------------------

// Individual constants, and the unit is in the name: a bound whose unit lives
// in a comment is a bound that gets read as the other one. A byte cap is bytes
// and a text bound is code points, and the two are never conflated.
//
// The upload cap is checked against `file.size` before the first byte is sent.
// It is not the enforcement — anvil enforces during the stream, because a
// client-side check is a check an attacker skips.
export const kUploadMaxBytes = 26214400;
export const kBodyMaxBytes = 262144;
export const kPageLimitMax = 100;

// --- routes -----------------------------------------------------------------

// Every route's SHAPE is a type, and types are erased: a shape cannot leak
// because at run time it does not exist. What is emitted as a value is decided
// by visibility, and only there.
export type RouteId =
    | "auth.login"
    | "auth.me"
    | "applications.apply"
    | "applications.list"
    | "teams.list"
    | "content.get";

// Reachable with no credential at all — the paths below are values.
export type PublicRouteId =
    | "auth.login"
    | "auth.me"
    | "applications.apply"
    | "applications.list"
    | "teams.list"
    | "content.get";

// Everything else. The id is here, the path is not: it arrives with the session,
// filtered by the server to what this holder's permissions actually reach, so a
// content editor never learns the addresses of the routes above them.
export type HolderRouteId = never;

// The path parameters of each route, whatever its visibility. A holder route's
// parameters are as safe to emit as its id: this is a type, and it is gone by
// the time a bundle exists.
export type RouteParams = {
    readonly "auth.login": Record<string, never>;
    readonly "auth.me": Record<string, never>;
    readonly "applications.apply": Record<string, never>;
    readonly "applications.list": Record<string, never>;
    readonly "teams.list": Record<string, never>;
    readonly "content.get": Record<string, never>;
};

// The capability scope each route consumes, or null.
export type RouteCapability = {
    readonly "auth.login": null;
    readonly "auth.me": null;
    readonly "applications.apply": null;
    readonly "applications.list": null;
    readonly "teams.list": null;
    readonly "content.get": null;
};

// What a route answers with, for the routes anvil DECLARED an answer for.
//
// These are not a guess at the handler. anvil writes a described body through a
// response binder, where writing a key that is not next, writing one of the
// wrong type or stopping before the last field are compile errors on the SERVER
// — so the schema is a description of the bytes rather than a claim about them,
// which is the only condition under which generating types from one is better
// than generating none. A type nothing enforces is a lie that type-checks.
//
// A route with no declaration is absent here and resolves to `unknown`, which
// forces its call sites to narrow loudly rather than inherit that lie. Declare
// one in your application the way this interface was augmented before anvil
// emitted any of them:
//
//     declare module "./hammer.generated.js" {
//         interface RouteResponses {
//             "content.get": { readonly id: string };
//         }
//     }
export interface RouteResponses {}

export type ResponseOf<Id extends RouteId> = Id extends keyof RouteResponses
    ? RouteResponses[Id]
    : unknown;

// One `const` per route. A screen that calls two routes ships two, and a bundle
// an anonymous visitor can fetch carries neither the ids nor the facts of the
// rest — which is a property of the emission shape, not of the bundler's
// configuration.
//
// `method` and `path` are null for a holder route in every bundle. There is no
// table of them anywhere in this file, deliberately: an aggregate would put
// every route's facts into any bundle that touched one of them.
export const routeAuthLogin = {
    id: "auth.login",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/auth/login",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: false,
    page: null,
} as const;

export const routeAuthMe = {
    id: "auth.me",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/api/auth/me",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

export const routeApplicationsApply = {
    id: "applications.apply",
    access: "public",
    visibility: "public",
    method: "POST",
    path: "/api/applications",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: false,
    page: null,
} as const;

export const routeApplicationsList = {
    id: "applications.list",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/api/applications_list",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: { cursor: "_id", limitMax: 100 },
} as const;

export const routeTeamsList = {
    id: "teams.list",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/api/teams",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: { cursor: "_id", limitMax: 100 },
} as const;

export const routeContentGet = {
    id: "content.get",
    access: "public",
    visibility: "public",
    method: "GET",
    path: "/api/content",
    perms: [],
    capability: null,
    rateLimit: null,
    idempotent: true,
    page: null,
} as const;

// The public tier as one table, for a client that resolves an id at run time.
// Only this tier can be a table at all — a holder route has no path to put in
// one — and a consumer that wants the whole table pays for the whole table,
// which is the choice being offered rather than made for them.
export const publicRoutes = {
    "auth.login": routeAuthLogin,
    "auth.me": routeAuthMe,
    "applications.apply": routeApplicationsApply,
    "applications.list": routeApplicationsList,
    "teams.list": routeTeamsList,
    "content.get": routeContentGet,
} as const;

// --- the client -------------------------------------------------------------

// What this client knows, as ONE type parameter rather than four. Every call is
// then typed by the route `const` it names: a route that does not exist cannot
// be spelled, a parameter cannot be omitted, and a route declaring a capability
// scope will not compile without a `Capability` for that scope.
//
// A route with no `RouteResponses` declaration resolves to `unknown` here, which
// forces its call sites to narrow loudly rather than inherit a lie.
//
// `hash` is what PAIRS this type with the tables below it. It is a literal type,
// so two applications with two generated modules cannot cross them: the tables
// carry one descriptor's hash and the type demands that descriptor's hash, and a
// mismatch is a compile error at `createClient` rather than a client decoding one
// server's vocabulary against another's. Two modules generated from the SAME
// descriptor pair freely, which is correct — they are the same tables.
//
//     import { createClient } from "hammer/wire";
//     import { kApiTables, routeAuthRefresh } from "./hammer.generated.js";
//     import type { Api } from "./hammer.generated.js";
//
//     const client = createClient<Api>({
//         api: kApiTables,
//         refreshRoute: routeAuthRefresh,
//         origin: { pageOrigin: location.origin, apiOrigin, site: null },
//         fetch: window.fetch.bind(window),
//         session: sessions.source,
//     });
export type Api = {
    readonly params: RouteParams;
    readonly responses: { readonly [Id in RouteId]: ResponseOf<Id> };
    readonly code: ErrorCode;
    readonly reason: ValidationReason;
    readonly hash: typeof kTablesHash;
};

// One descriptor's tables, as one member. They are generated together and they
// are handed over together, so the set a client decodes with is the set whose
// hash is checked against the server's.
//
// An object literal over the constants above — no call and no import — so a
// bundle that references none of this still drops all of it, and this module
// still depends on nothing.
//
// `hash` is the sixth member and it is not decoded with: it is the descriptor
// this set came from, as a value, so that `Api` above can demand the same one.
// Without it the pairing was a CONVENTION — both names come out of one file — and
// a convention holds until an application has two generated modules.
//
// `refreshRoute` is deliberately NOT in here. The descriptor does not say which
// route a refresh goes to, so putting one in would be this generator guessing at
// an id; the application names it, and naming it is one line.
export const kApiTables = {
    codes: kErrorCodeValues,
    reasons: kValidationReasonValues,
    rateLimits: kRateLimits,
    singleUse: kCapabilitySingleUse,
    bodyMaxBytes: kBodyMaxBytes,
    hash: kTablesHash,
} as const;

// --- field types ------------------------------------------------------------

// What a form definition's fields may declare. The renderer is hammer's and
// the table is the application's: a field type is machinery — a control, a
// validation rule, an answer shape — and the particular set an application
// declares is not.
export type FieldTypeName = never;

// The JSON shape an answer arrives in and is read back as. A PII type has
// `null` here rather than a kind: its value is never echoed back, so a
// renderer told `"text"` renders a control for a value that has silently
// emptied itself.
export type AnswerKind = never;

// One table rather than one `const` per type, because the lookup is by the
// `code` a definition carries at run time: every consumer that renders a form
// resolves a type it was handed rather than one it spelled, so there is no
// bundle in which a subset of this table is the useful part.
//
// `defaultCodePoints` is CODE POINTS, as its name says, and it is the number
// the server checks against. A client enforcing it in UTF-16 code units
// refuses text the server would have accepted, which for any non-Latin script
// is most of it.
//
// The flags are named booleans and not the byte anvil stores, for the reason
// everything else here is a name: a client carrying a copy of a bitmask is a
// client carrying a copy of an enum.
export const kFieldTypes = {
} as const;

// --- sections ---------------------------------------------------------------

// The editable surface: what a section holds, what bounds each field is under,
// and which image slots it offers.
//
// `labels` is the one place the descriptor carries words a person reads, and it
// is not an exception to the rule that hammer ships none. They are the
// application's own labels for its own editors, declared once in the
// application's own table and generated from there — which is the opposite of a
// library shipping a string and of an application keeping a second copy of a
// table. They are indexed by the LOCALE TABLE's order, which is persisted and
// append-only, so index 0 means nothing in particular.
export type SectionKey = never;

// The control a field asks for. What it looks like is the application's — a
// mapping is not a component.
export type SectionFieldType = never;

// One `const` per section, because a screen that edits one section ships one
// section — and a section is the only table here whose rows carry words, in
// every declared locale, which is the difference between a few hundred bytes
// and all of them.

// The whole registry, for an editor that lists what there is to edit rather
// than knowing. A consumer that wants every section pays for every section,
// which is the choice being offered rather than made for them.
export const sections = {} as const;

// --- notification topics ----------------------------------------------------

// The same split the route table is under, applied to the other table that
// has one (`docs/01-seams.md` §4.1). A route's PATH is what calling it needs
// and a topic's KEY is what subscribing to it needs, so the key is the half
// withheld here — subscription is the disclosure, and a topic gated by a
// permission is one whose existence is part of what the permission protects.
//
// A bundle is a public file and a lazily loaded chunk is a public URL, so the
// key of a holder topic is in no bundle, no chunk and no source map. It
// arrives from the preferences endpoint, filtered by the server to the topics
// this holder may actually subscribe to, and a client re-attaches the entry it
// is given to the `const` below by CODE — which is why the code is emitted for
// every topic and the key is not.
//
// None of this is a boundary. anvil refuses the subscription, and for a topic
// that declares `stealthOnDenial` it refuses it the way it refuses a stealth
// route: as though the topic were not there.
export type TopicKey = never;

// Subscribable with no permission at all — the keys below are values.
export type PublicTopicKey = never;

// Everything else. The key is a type here and nowhere a value: this union is
// erased, and by the time a bundle exists there is nothing of it left.
export type HolderTopicKey = never;

export type TopicFanOut = never;

export type TopicScope = never;

// The transports anvil itself implements. A channel is not a row an
// application declares — adding one means shipping a sender — so this union is
// what the table holds and never more.
export type NotificationChannel = never;

// One `const` per topic. `userOptional` is false where the reader may not turn
// it off: a client that offers a switch there offers one the server refuses,
// and a security alert an account can silence is not an alert.
//
// `code` is a BIT POSITION in a stored preference mask and is append-only, the
// way a permission bit is. It is also the identity a holder topic is matched
// on, since its key is not here.

// The public tier as one table, for a client that resolves a key at run time.
// Only this tier can be a table at all — a holder topic has no key to put in
// one — which is the same sentence `publicRoutes` is under, for the same
// reason.
export const publicTopics = {} as const;

// --- analytics events -------------------------------------------------------

// What may be reported, and under what consent. One `const` per event and no
// table of them: a call site names the event it reports, so a screen that
// reports one ships one — and an aggregate would put every event's name into
// any bundle that touched a single one.
//
// `requiresConsent` is read at the door. An event that declares it is not
// queued pending a decision, because a buffer that flushes when consent
// arrives is a buffer of pre-consent data, which is the thing consent was
// about.
export type EventName = never;

export type EventClass = never;

// A dimension's values are the CLOSED set the server stores an index into, so
// the `as const` is what makes a typo a compile error rather than a row the
// ingest path drops — and a dropped row is the analytics defect nobody notices
// for a quarter.

// --- media ------------------------------------------------------------------

// A role is what an image is FOR, and it is the whole public grammar:
// `GET /media/{ns}/{id}/{role}`, built by the route builder and never by
// concatenation. The width is published BESIDE the role rather than instead of
// it, because a responsive `srcset` cannot exist without width descriptors —
// the browser has no basis on which to choose between the sources it is handed.
//
// Knowing a width was never the hazard. Building a URL out of one was, and
// there is no ladder here to build one from: no file extension, no format list,
// no rule from a width back to a path. A role→width mapping may change without
// a client release, and the addresses a client already holds keep working while
// it does.
//
// Bytes never enter the JS heap: this is an `<img src>` pointed at the media
// origin, not a fetch and a blob.
export type MediaNamespace =
    | "media";

export type MediaRole =
    | "thumb"
    | "card"
    | "hero"
    | "full";

// What a request with no role segment resolves to, and therefore what a caller
// that forgets the segment gets.
export const kMediaDefaultRole = "card";

// One table, because a namespace arrives with the object being rendered rather
// than being spelled at the call site.
export const kMediaWidths = {
    media: { thumb: 320, card: 640, hero: 1024, full: 1600 },
} as const;

// What each namespace will TAKE, which is the server's list and not a second
// one. It reaches two places and they have to agree: the `accept` attribute on
// a file input, which decides what the picker offers, and the check that runs
// against `File.type` before a byte is sent. An application that wrote this
// down itself kept a copy of something the server already enforces, and the
// copy is the one that goes stale — the symptom being an upload the picker
// offered and the server refused, or a file the picker hid and the server would
// have taken.
//
// Lowercase `type/subtype` with no parameters, which is the essence string a
// browser puts in `File.type`, so the comparison is `===` rather than a parse.
export const kMediaAccepts = {
    media: ["image/jpeg", "image/png", "image/webp", "image/avif"],
} as const;
